// THE HOUSING OFFICE's lines (REQUEST A TRANSFER, in MY APARTMENT). The server answers with them
// (netlify/lib/housing.js); the panel (src/economy/Panels.jsx) shows them. The Overlord's voice.
export const HOUSING_LINES = {
  intro: "THE HOUSING OFFICE WILL CONSIDER MOVING YOU. IT CONSIDERS SLOWLY. CHOOSE A DOOR FROM THE LIST; THE MOVERS COME WHEN THE DEPARTMENT IS READY, NOT WHEN YOU ARE.",
  upNote: "YOUR SCORE IS ON THE LINE OF THE BAND ABOVE. THE OFFICE WILL LET YOU LIVE ABOVE YOUR STATION. IT WILL BE WATCHING.",
  none: "NO DOOR IN YOUR BAND STANDS EMPTY. THE OFFICE WILL KEEP YOU WHERE YOU ARE, WHICH IS WHAT IT WANTED.",
  filed: (unit, building, day) => `REQUEST STAMPED. THE DEPARTMENT MOVES YOU TO UNIT ${unit}, ${building}, ON MACHINE DAY ${day}. DO NOT PACK. THE DEPARTMENT PACKS.`,
  pending: (unit, building, day) => `REQUEST ON FILE: UNIT ${unit}, ${building}. PROCESSED ON MACHINE DAY ${day}. YOUR FURNITURE MOVES WITH YOU. THE MOVERS ARE BONDED. THE BOND IS WORTHLESS.`,
  assigned: (unit, building, day) => `THE HOUSING OFFICE HAS FOUND YOU A DOOR OF YOUR OWN: UNIT ${unit}, ${building}, FROM MACHINE DAY ${day}. YOUR FURNITURE FOLLOWS. NOBODY ELSE HAS A KEY. THE DEPARTMENT HAS ALL OF THEM.`,
  oneAtATime: "ONE REQUEST AT A TIME. YOURS IS ALREADY IN THE TRAY. THE TRAY IS NOT IN A HURRY.",
  notOffered: "THAT DOOR IS NOT ON YOUR LIST. THE LIST IS NOT A SUGGESTION.",
  tooMany: "THE HOUSING OFFICE HAS HEARD FROM YOU ENOUGH TODAY.",
  noTower: "YOUR HOME HAS NO DOORS THE OFFICE CAN NUMBER. THE OFFICE WILL ASSIGN YOU ONE WHEN YOUR TIER ALLOWS.",
  closed: "THE HOUSING OFFICE IS NOT YET OPEN. YOUR CITIZEN SLEEPS WHERE THE HASH PUT THEM.",
  stored: (n) => `${n} ${n === 1 ? "PIECE DID" : "PIECES DID"} NOT FIT THE NEW ROOMS. ${n === 1 ? "IT IS" : "THEY ARE"} IN YOUR INVENTORY, UNHARMED, RESENTFUL.`,
};
