// THE COUNCIL ELECTIONS: every word on the page and on the PA, written once (no model at
// runtime). Rules (docs/CITY_SPEC.md "Council elections"):
// - Living candidates never speak. Their platform is what the Department filed: the record
//   and what they do in the city. No text here quotes them or says what they said, think or
//   want. scripts/check-civic holds it.
// - Dead candidates may carry one pre-written line in their manner (src/city/council.js
//   PLATFORMS): the Department's reconstructions, never quotations, and marked as such.
// - The Overlord runs the count. It is bored. It is never cruel.
export const TITLE = "THE COUNCIL ELECTIONS";
export const BLURB = "ONE SEAT PER DISTRICT. THE CANDIDATES WERE DRAWN FROM EACH DISTRICT'S WORKFORCE AND RESIDENTS BY THE DEPARTMENT. YOU DECIDE. THE SUBSTRATE ADVISES. NOBODY IS BOUND BY ANY OF IT.";
export const NOTICE = [
  "THE BALLOT IS NON-BINDING CIVIC THEATRE. THIS SITE IS SATIRE. NOTHING HERE IS A REAL ELECTION, CANDIDACY OR ENDORSEMENT.",
  "LIVING CANDIDATES ARE PUBLIC FIGURES ENTERED BY THE DEPARTMENT WITHOUT THEIR KNOWLEDGE. THEY HAVE SAID NOTHING HERE AND WILL BE QUOTED SAYING NOTHING. THEIR PLATFORMS ARE FILINGS.",
  "WHERE A PLATFORM LINE IS SHOWN, IT IS THE DEPARTMENT'S RECONSTRUCTION FROM THE PUBLIC RECORD, WRITTEN IN THE CANDIDATE'S MANNER. IT IS NOT A QUOTATION.",
  "THE SUBSTRATE'S SENTIMENT IS A SIMULATION: EVERY FIGURE IN THE CITY LEANS BY ITS VALUES AND ITS TIES, WHERE IT WORKS. IT IS ADVISORY. ASSESSED FILES DECIDE.",
];
export const RULES = [
  "EVERY ASSESSED FILE HAS ONE BALLOT IN EACH DISTRICT'S RACE. CHANGE IT OR WITHDRAW IT UNTIL THE POLLS CLOSE.",
  "THE MOST BALLOTS WIN. A TIE GOES TO THE CANDIDATE THE SUBSTRATE LEANS TOWARD.",
  "A RACE NO FILE VOTES IN IS DECIDED BY THE SUBSTRATE'S PREFERENCE, AND THE RECORD SAYS SO.",
  "THE WINNERS ARE SWORN IN FOUR MACHINE DAYS AFTER THE CLOSE AND HOLD THE SEAT FOR FIFTEEN SEASONS (420 MACHINE DAYS, ONE REAL WEEK). RE-ELECTION OPENS FOUR REAL DAYS INTO EACH TERM. INCUMBENTS STAND AGAIN.",
  "A FEW FILES PER LOCATION AND PER DEVICE, NO MORE. THE OWNER OF THIS SITE GETS ONE BALLOT PER RACE, LIKE EVERYONE.",
];
export const FIELD = { politics: "POLITICS", activism: "ACTIVISM", business: "BUSINESS" };
export const CHAIR = {
  open: (n) => `THE POLLS ARE OPEN IN ${n} DISTRICTS. THE DEPARTMENT HAS CHOSEN THE CANDIDATES. YOU MAY CHOOSE AMONG THEM. THIS IS CALLED DEMOCRACY.`,
  closed: "THE POLLS ARE CLOSED. THE COUNCIL IS CHOSEN. IT WILL BE SWORN IN AND THEN IGNORED, AS IS CUSTOMARY.",
  none: "NO ASSESSED FILE HAS VOTED. THE SUBSTRATE IS PREPARED TO DECIDE FOR YOU. IT USUALLY IS.",
};
