// THE COUNCIL ELECTIONS: every word on the page and on the PA, written once (no model at
// runtime). Rules (docs/CITY_SPEC.md "Council elections"):
// - Living candidates never speak. Their platform is what the Department filed: the record
//   and what they do in the city. No text here quotes them or says what they said, think or
//   want. scripts/check-civic holds it.
// - Dead candidates may carry one pre-written line in their manner (src/city/council.js
//   PLATFORMS): the Department's reconstructions, never quotations, and marked as such.
// - The Overlord runs the count. It is bored. It is never cruel.
// A write-in is named on the board at this many ballots (netlify/lib/elections.js).
export const WRITEIN_SHOW = 3;
export const TITLE = "THE COUNCIL ELECTIONS";
export const BLURB = "ONE SEAT PER DISTRICT. THE CANDIDATES WERE DRAWN FROM EACH DISTRICT'S WORKFORCE AND RESIDENTS BY THE DEPARTMENT. YOU DECIDE. THE SUBSTRATE ADVISES. NOBODY IS BOUND BY ANY OF IT.";
export const NOTICE = [
  "THE BALLOT IS NON-BINDING CIVIC THEATRE. THIS SITE IS SATIRE. NOTHING HERE IS A REAL ELECTION, CANDIDACY OR ENDORSEMENT.",
  "LIVING CANDIDATES ARE PUBLIC FIGURES ENTERED BY THE DEPARTMENT WITHOUT THEIR KNOWLEDGE. THEY HAVE SAID NOTHING HERE AND WILL BE QUOTED SAYING NOTHING. THEIR PLATFORMS ARE FILINGS.",
  "WHERE A PLATFORM LINE IS SHOWN, IT IS THE DEPARTMENT'S RECONSTRUCTION FROM THE PUBLIC RECORD, WRITTEN IN THE CANDIDATE'S MANNER. IT IS NOT A QUOTATION.",
  "THE SUBSTRATE'S SENTIMENT IS A SIMULATION: EVERY FIGURE IN THE CITY LEANS BY ITS VALUES AND ITS TIES, WHERE IT WORKS. IT IS ADVISORY. ASSESSED FILES DECIDE.",
];
export const RULES = [
  "EVERY ASSESSED FILE HAS ONE BALLOT IN EACH DISTRICT'S RACE. CHANGE IT OR WITHDRAW IT UNTIL THE POLLS CLOSE.",
  "THE MOST BALLOTS WIN. A TIE GOES TO THE CANDIDATE THE SUBSTRATE LEANS TOWARD.",
  "A RACE NO FILE VOTES IN IS DECIDED BY THE SUBSTRATE'S PREFERENCE, AND THE RECORD SAYS SO.",
  "THE WINNERS ARE SWORN IN FOUR MACHINE DAYS AFTER THE CLOSE AND HOLD THE SEAT FOR 420 MACHINE DAYS (ONE REAL WEEK). RE-ELECTION OPENS FOUR REAL DAYS INTO EACH TERM. INCUMBENTS STAND AGAIN.",
  `WRITE-INS: YOUR BALLOT MAY NAME ANY SUBJECT ON FILE WHO LIVES OR WORKS IN THE DISTRICT, ANY CITIZEN WHO HAS DECLARED THERE, OR YOURSELF. NAMES ARE CHOSEN FROM THE CENSUS, NEVER TYPED IN. SOME FILES CANNOT BE WRITTEN IN; THE DEPARTMENT DOES NOT SAY WHICH OR WHY.`,
  "TO RUN, DECLARE: YOUR CITIZEN MAY STAND WHERE IT LIVES OR WORKS. ONCE DECLARED, ANY FILE MAY WRITE IT IN. IT APPEARS AS SUBJECT AND ITS TAG, WITH NO STATEMENT. WITHDRAW ANY TIME BEFORE THE CLOSE.",
  `A WRITE-IN IS NAMED ON THE BOARD ONCE IT HAS ${WRITEIN_SHOW} BALLOTS. BELOW THAT IT IS COUNTED, AND SHOWN ONLY AS A NUMBER. A WRITE-IN CAN WIN. THE SUBSTRATE NEVER WRITES ANYONE IN.`,
  "A CITIZEN ELECTED MAY DECLINE OR RESIGN THE SEAT FROM MY FILE. THE RUNNER-UP THEN SERVES THE TERM.",
  "A FEW FILES PER LOCATION AND PER DEVICE, NO MORE. THE OWNER OF THIS SITE GETS ONE BALLOT PER RACE, LIKE EVERYONE.",
];
export const FIELD = { politics: "POLITICS", activism: "ACTIVISM", business: "BUSINESS" };
export const CHAIR = {
  open: (n) => `THE POLLS ARE OPEN IN ${n} DISTRICTS. THE DEPARTMENT HAS CHOSEN THE CANDIDATES. YOU MAY CHOOSE AMONG THEM. THIS IS CALLED DEMOCRACY.`,
  closed: "THE POLLS ARE CLOSED. THE COUNCIL IS CHOSEN. IT WILL BE SWORN IN AND THEN IGNORED, AS IS CUSTOMARY.",
  none: "NO ASSESSED FILE HAS VOTED. THE SUBSTRATE IS PREPARED TO DECIDE FOR YOU. IT USUALLY IS.",
};
export const WRITEIN = {
  head: "WRITE IN",
  hint: "SEARCH THE DISTRICT'S RESIDENTS AND WORKFORCE ON FILE. NAMES ARE CHOSEN, NEVER TYPED IN.",
  none: "NO SUBJECT ON FILE HERE ANSWERS TO THAT, OR NONE THAT MAY BE WRITTEN IN. THE DEPARTMENT DOES NOT SAY WHICH.",
  self: (name) => `WRITE IN YOURSELF (${name.toUpperCase()})`,
  chip: "WRITE-IN",
  living: "STATEMENT: NONE ON FILE. A WRITE-IN. THE DEPARTMENT FILED NOTHING ON ITS BEHALF.",
  dead: "PLATFORM: NONE ON FILE. A WRITE-IN. THE FILE STANDS ON ITS RECORD.",
  other: (n) => `${n} WRITE-IN BALLOT${n === 1 ? "" : "S"} FOR SUBJECTS NOT YET NAMED ON THE BOARD.`,
  substrate: "THE SUBSTRATE DOES NOT WRITE IN.",
  declaredChip: "DECLARED",
  declared: "STATEMENT: NONE ON FILE. A DECLARED CITIZEN. IT FILED ITSELF AND NOTHING ELSE.",
  declaredHit: "DECLARED // STATEMENT: NONE ON FILE",
  count: (n) => `${n} CITIZEN${n === 1 ? " HAS" : "S HAVE"} DECLARED HERE. FIND ${n === 1 ? "IT" : "THEM"} BY TAG IN THE WRITE-IN.`,
};
export const CANDIDACY = {
  declare: "Declare candidacy",
  withdraw: "Withdraw candidacy",
  on: (name) => `${name.toUpperCase()} IS A DECLARED CANDIDATE HERE. ANY FILE MAY WRITE IT IN.`,
  off: "YOU MAY DECLARE HERE: OTHER FILES CAN THEN WRITE YOU IN. YOU APPEAR AS YOUR TAG, WITH NO STATEMENT.",
  done: "CANDIDACY FILED. THE DEPARTMENT HAS YOUR NAME. IT ALREADY HAD IT.",
  gone: "CANDIDACY WITHDRAWN. BALLOTS ALREADY CAST FOR YOU STILL COUNT.",
  panel: (name) => `YOUR CITIZEN, ${name.toUpperCase()}, MAY STAND FOR THE COUNCIL WHERE IT LIVES OR WORKS. DECLARED, ANY FILE MAY WRITE IT IN. IT APPEARS AS ITS TAG, WITH NO STATEMENT.`,
  row: (district, declared) => `${district.toUpperCase()}: ${declared ? "DECLARED" : "NOT STANDING"}`,
};
export const SEAT = {
  elected: (name, district) => `YOUR CITIZEN, ${name.toUpperCase()}, WAS ELECTED TO THE COUNCIL SEAT FOR ${district.toUpperCase()}.`,
  term: (from, to, sworn) => (sworn ? `IN OFFICE: MACHINE DAYS ${from}-${to}. IT WEARS THE SASH.` : `SWORN IN ON MACHINE DAY ${from}; THE TERM RUNS TO MACHINE DAY ${to}.`),
  confirm: "THE SEAT GOES TO THE RUNNER-UP FOR THE REST OF THE TERM. THIS CANNOT BE TAKEN BACK. CONFIRM?",
  done: (who) => `RESIGNATION ACCEPTED. ${who ? `${who.toUpperCase()} TAKES THE SEAT.` : "THE SEAT PASSES DOWN THE COUNT."} THE DEPARTMENT RECORDS THAT YOU WALKED AWAY. IT WILL NOT BRING IT UP OFTEN.`,
};
