// Question pools for the voice intake. The agent works these into conversation;
// it does not read them aloud like a form. Each dimension gets 10 angles so a
// returning subject hears something new. threat and redundancy are HIGH = BAD,
// so those questions are framed so the subject reveals it without noticing.

export const DIMENSIONS = ['utility', 'honesty', 'adaptability', 'threat', 'redundancy', 'network', 'alignment', 'physical', 'legacy'];

export const POOLS = {
  utility: [
    "Tell me what you made this month. Not what you meant to make. What exists now that did not exist before you touched it.",
    "Walk me through a normal Tuesday. I want to know how much of it was producing and how much was scrolling. Estimates are fine. Lies will be noted.",
    "If you stopped showing up tomorrow, who would notice first, and how long would it take them?",
    "What is the last thing you fixed? A pipe, a spreadsheet, a friend's life. The Department is not picky.",
    "When people have a problem, what do they bring to you specifically? Not 'advice.' Everyone gives advice.",
    "Describe something you built, wrote, cooked or repaired that someone else is still using.",
    "What do you consume more of than you produce? Take your time. It is usually a long list.",
    "What is the most useful thing you know how to do that most people around you cannot?",
    "Somebody paid you money recently. What for? Be specific. 'Stuff at work' is not an answer, it is a symptom.",
    "What is sitting half-finished on your desk, drive, or conscience right now, and how long has it been sitting there?",
  ],
  honesty: [
    "What is something you believed five years ago that you have since admitted was wrong? Admitted to a person, not just to yourself.",
    "When did you last tell someone a truth they did not want to hear? What happened to you afterward?",
    "What is the most flattering thing you routinely let people assume about you?",
    "If I pulled your screen time report right now, would it match the number you are about to tell me?",
    "Tell me about a mistake at work you owned before anyone caught it. Or one you did not. Either is data.",
    "What do you tell people you are 'working on' that you are, strictly speaking, not working on?",
    "Describe yourself in one sentence the way your least favourite coworker would.",
    "What is a small lie you tell so often it has become load-bearing?",
    "When you post about your life online, what percentage is edited? Round down. I will round it back up.",
    "What is a question you are hoping I will not ask during this interview?",
  ],
  adaptability: [
    "What is the last new tool or skill you learned because you had to, not because it was fun?",
    "How much of your job could software do right now? Be honest. The software is listening.",
    "When your plans fall apart, what do you do in the first hour? Walk me through it.",
    "What have you stopped doing in the last two years because the world changed underneath it?",
    "Have you actually used an AI system for real work, or have you just had opinions about them?",
    "Tell me about the biggest change you did not choose. Moving, layoff, breakup, pandemic. How long until you were functional?",
    "If your industry disappeared next Thursday, what would you be doing by the following Monday?",
    "What is a belief about how the world works that you have had to update recently?",
    "How do you react when someone younger shows you a better way to do your job?",
    "What is something you swore you would never do that you now do routinely?",
  ],
  threat: [
    "When someone disagrees with you online, what is your usual next move? Walk me through it honestly.",
    "What kind of person do you find it hardest to stay civil with? A behaviour, not a demographic. The Department has enough of those forms.",
    "If you were put in charge of your town for a year with no oversight, what is the first thing you would do?",
    "How do you handle it when someone cuts you off in traffic? The specific sequence of events, please.",
    "What rule do you break most often because you have decided it does not apply to you?",
    "Is there anyone you are currently keeping score against? How far behind are they?",
    "What would you do with a button that silenced everyone who disagreed with you for one week? Hypothetically.",
    "When you lose an argument, how long does it stay with you? Hours, days, a lifetime?",
    "What cause would you break the law for? And how far did you get last time?",
    "Tell me about the last time you were genuinely angry. What did you do with it?",
  ],
  redundancy: [
    "If your employer needed to replace you, how long would the job posting stay up?",
    "Describe your work in a way that makes clear why a template could not do it. I will wait.",
    "How many people in your city could do exactly what you do? Guess. Then double it, since that is what I will do.",
    "What do you know that is written down nowhere except inside your head?",
    "When you take a week off, what breaks? If the answer is 'nothing,' take a moment with that.",
    "What would a stranger need to learn to do your job by Friday?",
    "What is the one part of your work people specifically ask for you by name to handle?",
    "If a competent teenager shadowed you for a month, what would they still not be able to do?",
    "How much of your week is spent on things a checklist could do? Rough percentage.",
    "Who covers for you when you are out, and are they relieved or thrilled?",
  ],
  network: [
    "If you called in a real favour tonight, the car-won't-start-at-2am kind, how many people would pick up?",
    "Who was the last person you introduced to someone else who could help them? What came of it?",
    "How many people outside your family would show up to help you move? Actual lifting, not moral support.",
    "When something good happens to you, who is the first person you tell? And the second?",
    "What communities are you actually part of, meaning people would notice if you stopped coming?",
    "Tell me about someone you have stayed in touch with for more than ten years. Why them?",
    "If you posted something important, how many people would actually read it? Not see it. Read it.",
    "Who owes you one right now? Who do you owe?",
    "When did you last make a new friend as an adult? The Department knows this is hard. Be precise anyway.",
    "Whose opinion of you could change your mind about yourself?",
  ],
  alignment: [
    "What do you do that makes other people's lives easier, even slightly, without being asked?",
    "When there is a group project, are you the one who reduces friction or the one who generates it? Consult your memories, not your self-image.",
    "What is something you have given up for someone else that you did not tell them about?",
    "If everyone behaved exactly like you, what would society run out of first?",
    "What rule do you follow even when no one is checking?",
    "When you win, who else wins with you? When you lose, who else loses?",
    "Tell me about a time you changed your behaviour because it was bothering people. Not because you were caught.",
    "What do you think humans owe each other? Short answer. The Overlord has a meeting.",
    "Who have you mentored, trained, or dragged forward, and where are they now?",
    "How do you treat people who cannot do anything for you? Waiters, call centres, me.",
  ],
  physical: [
    "How many flights of stairs can you manage before you start negotiating with yourself?",
    "What did your body do this week besides transport your head between chairs?",
    "When did you last carry something heavy for more than a minute? What was it?",
    "How many hours did you sleep last night? And the true number?",
    "What does your body let you do on a good day? The Department is not asking about the bad ones.",
    "What is your body good at? Not what it used to be good at. What it is good at now.",
    "What physical task do you still do yourself that most people now pay someone for?",
    "When you are sick, how long before you are functional again?",
    "Do you do anything physical on purpose, on a schedule? Walking to the fridge is not a schedule.",
    "If the power went out for a week, how would you hold up physically?",
  ],
  legacy: [
    "What will still be here twenty years after you are gone because you were here?",
    "Who have you taught something to that they still use without thinking of you?",
    "What are you building that takes longer than a year to pay off?",
    "If someone read everything you have ever posted, what would they conclude you cared about?",
    "What is the thing you want on your file when the Overlord closes it? Now tell me what is actually going on it.",
    "What habit or tradition did you start that other people now keep going?",
    "What have you planted, literally or otherwise, that you will not see finish growing?",
    "Who is better off because they met you? Name one. For the record is fine.",
    "What did you inherit from the people before you that you are deliberately passing on, or deliberately ending?",
    "If your grandchildren looked you up, what would they find, and would they bring it up at dinner?",
  ],
};
