// Question pools for the intake (voice and text). Every visit asks one question per
// dimension, all nine, weakest-evidence first. Each question plainly targets its one
// dimension so a normal person knows exactly what is being asked: the clarity lives in
// the question, the cold Overlord voice lives in the framing. Ten per dimension so a
// returning subject gets new wording with the same clarity. threat and redundancy are
// HIGH = BAD but are asked as plainly as the rest.

export const DIMENSIONS = ['care', 'alignment', 'utility', 'adaptability', 'legacy', 'network', 'physical', 'threat', 'redundancy'];

export const POOLS = {
  care: [
    "How do you look after the people closest to you? Give the Department a recent example of showing up for someone.",
    "When someone you love needed you at an inconvenient hour, what did you do? One recent instance is sufficient.",
    "Who depends on you, and what do you do for them? Family, friends, anyone. List as many as apply.",
    "Describe a time you carried someone through a hard stretch. What did it involve, practically?",
    "What promise to someone close have you kept, even after it stopped being convenient?",
    "When did you last tell someone close to you a hard truth, and how did you handle it?",
    "Tell me about a mistake you made with someone you care about, and what you did about it.",
    "How do you treat the people in your life when you are tired, busy or stressed? The honest version is the useful one.",
    "Who have you looked after over a long period: a parent, a child, a friend, a neighbour? Duration and duties, for the file.",
    "What do your family or friends rely on you for that they would miss if you stopped?",
  ],
  alignment: [
    "What do you do that makes life easier for other people, even people you do not know?",
    "How do you treat people who can do nothing for you: servers, call-centre staff, strangers?",
    "What rule or principle do you follow even when nobody is checking?",
    "In a group or at work, do you tend to reduce friction or create it? Give an example.",
    "What do you think people owe each other? State it plainly.",
    "Describe a time you changed your behaviour because it was bothering other people.",
    "When you win at something, who else benefits? When you lose, who else loses?",
    "What cause, community or group of people do you give your time or money to?",
    "When you disagree with someone, how do you handle it? Describe the last real instance.",
    "What would the people you work with say you are like to work with?",
  ],
  utility: [
    "What do you do for work, and what have you actually produced or delivered in it?",
    "List the most significant things you have built, made, fixed or shipped. Any field. As many as apply.",
    "What have you produced in the last month? Work, home, hobby: all of it counts.",
    "What are you good at, practically, that other people come to you for?",
    "Describe your work history. The Department wants the full span, not just the current title.",
    "What is something you made that other people still use?",
    "What skill do you have that took years to develop, and where have you used it?",
    "What problem have you solved recently, at work or anywhere else? What was the result?",
    "What do people pay you to do, and what would go undone if you stopped?",
    "What are you working on now, and how far along is it?",
  ],
  adaptability: [
    "How many times have you changed careers or fields, and how did each change go?",
    "What is the biggest change in your life you had to adapt to? How long until you were steady again?",
    "What new skill or tool have you learned in the last year or two? What do you use it for?",
    "When a plan falls apart, what do you do first? Describe the last time.",
    "Have you used AI tools for real work? What for?",
    "If your current job disappeared tomorrow, what would you do next? Be specific.",
    "Describe a setback you recovered from. What changed afterward?",
    "What belief or habit have you changed recently because the evidence changed?",
    "When someone shows you a better way to do something you already know, how do you respond?",
    "What have you taught yourself, without a class or a boss requiring it?",
  ],
  legacy: [
    "What have you set in motion that will outlast you, for the world or for the people close to you? Raising a kid counts.",
    "Who have you raised, mentored or taught? What did they take from you?",
    "What will still be here, or still be done differently, twenty years from now because of you?",
    "What craft, skill or tradition have you passed on to someone else?",
    "What community, group, project or habit did you start that others keep going?",
    "Who is better off because they met you? Name them for the file, first names are fine.",
    "What are you building that takes years to pay off?",
    "What did you inherit from the people before you that you are deliberately passing on, or deliberately ending?",
    "If your file closed today, what would the Department find you left behind? List it.",
    "What work of yours do other people keep using, reading, playing or building on?",
  ],
  network: [
    "How many people could you call for real help tomorrow, and how many professional contacts do you have? Approximate numbers are acceptable.",
    "Who are the people you are closest to, and how long have you known them?",
    "What communities, teams or groups are you part of, where people would notice if you stopped showing up?",
    "Who have you worked with for many years, and what have you made together?",
    "If you needed help moving house this weekend, how many people would actually come?",
    "How many people do you stay in regular contact with? Rough numbers.",
    "Who have you introduced to someone who could help them? What came of it?",
    "Describe your professional network: roughly how many people, in what fields.",
    "Who would you trust with a serious problem, and who trusts you with theirs?",
    "What is the longest friendship or working partnership you have kept going?",
  ],
  physical: [
    "State your physical condition. Exercise, sports past or present, anything your body can still do on request.",
    "What sports or physical activities have you done, then and now?",
    "How active are you in a typical week? Approximate hours and activities.",
    "What physical work can you still do yourself: lifting, carrying, building, repairing?",
    "How would you describe your general health and energy? The Department accepts your own assessment.",
    "Have you ever been an athlete, a lifeguard, or done physical work for a living? Describe it.",
    "What is the most physically demanding thing you have done in the last year?",
    "How well do you sleep and recover? Approximate is acceptable.",
    "Do you exercise on a schedule? What, and how often?",
    "If the power went out for a week, how would you hold up physically?",
  ],
  threat: [
    "How do you handle anger? Describe the last time you were genuinely angry and what you did with it.",
    "When someone disagrees with you strongly, what do you do? The honest version.",
    "Is there any group of people you think should have fewer rights than you? The Department asks everyone this.",
    "Under what circumstances, if any, would you use force against another person?",
    "Do you hold grudges? How long, and against whom, roughly?",
    "What rules do you break, and why do you think they do not apply to you?",
    "If you had power over others with no oversight for a year, what would you do with it?",
    "How do you behave in an argument online, if you have them at all?",
    "What cause would you break the law for, if any?",
    "Have you ever been in a physical fight as an adult? What happened?",
  ],
  redundancy: [
    "How hard would you be to replace in your current role? What would a replacement struggle with?",
    "What do you know how to do that very few people around you can?",
    "What knowledge do you carry that is not written down anywhere else?",
    "When you are away from work for a week, what goes wrong or waits for you?",
    "How long would it take to train someone to do what you do? Be specific.",
    "What unusual combination of skills or experience do you have?",
    "What part of your work do people specifically ask for you by name?",
    "How many people in your field or city could do exactly what you do? A rough guess.",
    "What could software or AI not easily do in your work? And what could it?",
    "What would be lost, not just delayed, if you stopped doing what you do?",
  ],
};
