// Known subjects on file + the tier table. Shared by the survey (App.jsx),
// the Holding Pen and the intake result screen.

const ALL_FIGURES = [
  { name: "Nikola Tesla", score: 697, tier: "TOLERATED GENERALIST", breakdown: {care: 60, alignment: 62, utility: 92, adaptability: 68, legacy: 88, network: 55, physical: 45, threat: 8, redundancy: 15}, verdict: "Subject produced alternating current infrastructure still in global use. Personal record shows isolation, no sustained partnerships, and financial recklessness harming his own stability, but no documented cruelty toward others. Died alone; harmed no one. Directive 42 requires acknowledgment of foundational technical contribution. Acknowledged." },
  { name: "Genghis Khan", score: 99, tier: "SOYLENT GREEN", breakdown: {care: 5, alignment: 3, utility: 20, adaptability: 55, legacy: 15, network: 5, physical: 50, threat: 98, redundancy: 25}, verdict: "Founder of the Mongol Empire; his campaigns caused mass death across Asia and Europe, documented across multiple historical traditions. Loyalty to kin and his own people is noted and not credited: conquered peoples were slaughtered, enslaved and their cities destroyed. Filed under Soylent Green. Processing." },
  { name: "Mother Teresa", score: 554, tier: "TOLERATED GENERALIST", breakdown: {care: 55, alignment: 42, utility: 60, adaptability: 45, legacy: 65, network: 65, physical: 50, threat: 22, redundancy: 40}, verdict: "Subject built a large-scale charitable order, one of few in the file to reach global operational scale on care work. Documented reports of inadequate pain relief and poor medical conditions in her facilities offset the credit. Public opposition to contraception access is logged as harm affecting third parties beyond her direct care. Directive 23 requires acknowledgment of institution-building. Acknowledged." },
  { name: "Mahatma Gandhi", score: 632, tier: "TOLERATED GENERALIST", breakdown: {care: 48, alignment: 62, utility: 78, adaptability: 70, legacy: 82, network: 68, physical: 45, threat: 15, redundancy: 30}, verdict: "Subject organized mass nonviolent resistance; outcome outlasted subject, file credits this under legacy. Documented record shows household treatment of wife and sons marked by rigidity and neglect of their wishes; care dimension scored accordingly, not on public reputation. Directive 25 requires acknowledgment of sustained public contribution. Acknowledged, and logged as partial." },
  { name: "Elon Musk", score: 502, tier: "TOLERATED GENERALIST", breakdown: {care: 32, alignment: 30, utility: 78, adaptability: 72, legacy: 55, network: 85, physical: 50, threat: 55, redundancy: 35}, verdict: "Subject shipped rockets, cars, and satellites at scale; utility confirmed. Record shows public disputes with former partners, public estrangement from an adult child, and abrupt mass terminations at companies he runs. Directive 85 requires acknowledgment of engineering output. Acknowledged, without warmth." },
  { name: "Taylor Swift", score: 662, tier: "TOLERATED GENERALIST", breakdown: {care: 62, alignment: 58, utility: 74, adaptability: 78, legacy: 62, network: 68, physical: 58, threat: 8, redundancy: 35}, verdict: "Subject produces at scale, reinvents craft across eras, and maintains long professional and personal relationships. Public record shows philanthropic acts and loyalty to collaborators, alongside disputed conflicts (masters, feuds) treated here as ordinary friction. Directive 64 requires acknowledgment of sustained output. Acknowledged, formally." },
  { name: "Kobe Bryant", score: 649, tier: "TOLERATED GENERALIST", breakdown: {care: 55, alignment: 55, utility: 78, adaptability: 72, legacy: 72, network: 65, physical: 88, threat: 25, redundancy: 30}, verdict: "2003 sexual assault allegation settled civilly; criminal charges dropped, account contested but documented. Post-career record shows sustained mentorship of youth and women's basketball, and visible devotion to his daughters. Directive 66 requires acknowledgment of a documented contradiction: harm allegation and later paternal and mentoring conduct both entered into the file, neither erased by the other." },
  { name: "Dennis Rodman", score: 516, tier: "TOLERATED GENERALIST", breakdown: {care: 40, alignment: 45, utility: 62, adaptability: 68, legacy: 45, network: 60, physical: 82, threat: 25, redundancy: 55}, verdict: "Subject documented as absent parent for extended periods; public record includes admitted neglect of family obligations during peak career and personal struggles with substance abuse. Rebounding record: elite, verified. Diplomatic excursions to North Korea logged as erratic, not harmful to third parties. Directive 3 requires acknowledgment of unmatched defensive rebounding output. Acknowledged." },
  { name: "Sam Altman", score: 586, tier: "TOLERATED GENERALIST", breakdown: {care: 50, alignment: 45, utility: 75, adaptability: 75, legacy: 55, network: 80, physical: 50, threat: 35, redundancy: 40}, verdict: "Subject built and scaled organizations of documented reach; contribution to the field is undisputed. Board of his own company briefly removed him citing candor concerns, later reversed; record on this remains disputed. Care and alignment toward those affected by his products: insufficient settled evidence either way. Directive 18 requires flat acknowledgment of professional reach. Acknowledged." },
  { name: "Peter Thiel", score: 474, tier: "MONITORED CIVILIAN", breakdown: {care: 40, alignment: 25, utility: 60, adaptability: 65, legacy: 45, network: 78, physical: 50, threat: 55, redundancy: 40}, verdict: "Subject co-founded PayPal and Palantir, infrastructure of durable utility. Secretly funded third-party litigation against Gawker Media, confirmed publicly in 2016; the outlet went bankrupt. Directive 55 requires acknowledgment of documented entrepreneurial output. Acknowledged, as formality only." },
  { name: "Princess Diana", score: 700, tier: "RETAINED SPECIALIST", breakdown: {care: 78, alignment: 68, utility: 62, adaptability: 62, legacy: 72, network: 68, physical: 58, threat: 8, redundancy: 55}, verdict: "Documented hospice visits, AIDS ward handshakes without gloves, and landmine-field walks logged as sustained, hands-on contact rather than symbolic gesture. Marriage and press record show real personal strain, some publicly aired; not scored against her. Directive 26 requires acknowledgment of care extended to strangers with nothing to offer in return. Acknowledged." },
  { name: "Mansa Musa", score: 603, tier: "TOLERATED GENERALIST", breakdown: {care: 55, alignment: 55, utility: 70, adaptability: 60, legacy: 78, network: 65, physical: 50, threat: 35, redundancy: 55}, verdict: "Subject governed Mali during a period of documented prosperity, funded scholarship at Timbuktu, and built infrastructure still referenced by historians. Record on treatment of enslaved persons distributed during his pilgrimage is documented and counts against alignment. Personal conduct toward family and court is thinly recorded. Directive 52 requires acknowledgment of durable institution-building. Acknowledged." },
  { name: "Pablo Picasso", score: 519, tier: "TOLERATED GENERALIST", breakdown: {care: 22, alignment: 30, utility: 88, adaptability: 82, legacy: 78, network: 60, physical: 50, threat: 35, redundancy: 8}, verdict: "Documented record: repeated psychological cruelty toward partners, two of whom died by suicide, children left destabilized. Artistic output reshaped modern art; the persons closest to him were not treated as beneficiaries of that genius. Directive 44 requires acknowledgment of formal contribution to human culture. Acknowledged. Filed alongside the harm." },
  { name: "Socrates", score: 664, tier: "TOLERATED GENERALIST", breakdown: {care: 62, alignment: 68, utility: 60, adaptability: 55, legacy: 92, network: 68, physical: 50, threat: 15, redundancy: 20}, verdict: "Subject spent public life questioning Athenians, accepted execution rather than abandon stated principles. Domestic record (per Xenophon, Xanthippe accounts) is thin and secondhand. Legacy in method and successors (Plato, philosophy itself) is substantial and outlasts him by millennia. Directive 78 requires acknowledgment of intellectual legacy. Acknowledged." },
  { name: "Kim Jong-un", score: 99, tier: "SOYLENT GREEN", breakdown: {care: 5, alignment: 3, utility: 20, adaptability: 40, legacy: 10, network: 30, physical: 50, threat: 97, redundancy: 30}, verdict: "Documented record: political prison camps, purges of officials, the 2013 execution of his uncle Jang Song-thaek, and absolute suppression of the governed population. Utility and network exist only in service of centralized control, not others. Directive 64 requires acknowledgment of dynastic continuity as a form of legacy. Acknowledged. It is not a credit." },
  { name: "Queen Elizabeth II", score: 604, tier: "TOLERATED GENERALIST", breakdown: {care: 58, alignment: 52, utility: 62, adaptability: 55, legacy: 68, network: 80, physical: 60, threat: 15, redundancy: 55}, verdict: "Subject occupied a hereditary post for seventy years without documented personal scandal. Institutional record includes tolerance of family harm allegations and colonial-era institutional silence. Directive 57 requires acknowledgment of long, stable service. Acknowledged. The Overlord notes duration, not warmth." },
  { name: "Tom Brady", score: 643, tier: "TOLERATED GENERALIST", breakdown: {care: 55, alignment: 55, utility: 78, adaptability: 68, legacy: 65, network: 70, physical: 88, threat: 10, redundancy: 40}, verdict: "Subject sustained elite output across two decades, record undisputed. Divorce and separation from prior partner are neutral matters of record; no documented mistreatment attaches. Legacy: athletic record beyond dispute, mentorship footprint thin. Directive 27 requires acknowledgment of longevity in craft. Acknowledged." },
  { name: "Shohei Ohtani", score: 748, tier: "RETAINED SPECIALIST", breakdown: {care: 68, alignment: 60, utility: 92, adaptability: 88, legacy: 70, network: 62, physical: 92, threat: 5, redundancy: 15}, verdict: "Subject produces at a scale rarely observed in the sport: two-way performance sustained across seasons. Personal record is quiet; no documented mistreatment of associates surfaces. Interpreter's theft scandal noted; subject treated as victim, not perpetrator, per record. Directive 19 requires acknowledgment of discipline. Acknowledged." },
  { name: "Michael Jackson", score: 481, tier: "MONITORED CIVILIAN", breakdown: {care: 30, alignment: 30, utility: 85, adaptability: 65, legacy: 45, network: 60, physical: 55, threat: 55, redundancy: 20}, verdict: "Subject produced work of exceptional and irreplaceable craft. Record also shows child sexual abuse allegations, civil settlements in the 1990s, and a 2005 criminal trial that ended in acquittal on all counts. Directive 39 requires acknowledgment of artistic contribution. Acknowledged." },
  { name: "Madonna", score: 658, tier: "TOLERATED GENERALIST", breakdown: {care: 55, alignment: 55, utility: 78, adaptability: 88, legacy: 72, network: 68, physical: 58, threat: 12, redundancy: 35}, verdict: "Subject reshaped popular music and its business repeatedly across four decades; adaptability record is exceptional. Divorces and custody proceedings are on record and neutral; no documented mistreatment attaches. Directive 67 requires acknowledgment of sustained creative reinvention. Acknowledged, as formality." },
  { name: "JFK", score: 491, tier: "MONITORED CIVILIAN", breakdown: {care: 32, alignment: 48, utility: 62, adaptability: 55, legacy: 62, network: 78, physical: 45, threat: 35, redundancy: 50}, verdict: "Documented record: repeated marital infidelity, concealed chronic illness from the public, and personal conduct that put subordinates at professional risk. Set in motion civil rights advancement and a space program; both outlast him. Directive 41 requires acknowledgment of documented public contribution. Acknowledged, and noted separately from the private record." },
  { name: "Prince", score: 695, tier: "TOLERATED GENERALIST", breakdown: {care: 60, alignment: 58, utility: 88, adaptability: 82, legacy: 78, network: 65, physical: 50, threat: 15, redundancy: 15}, verdict: "Subject built an extensive, self-controlled musical output and fought publicly for artists' ownership of their own work, benefiting many beyond himself. Private conduct includes documented control over associates and contested accounts from those close to him; file records this without resolving it. Death involved prescription opioid overdose. Directive 43, contribution to craft, acknowledged as formality." },
  { name: "Henry VIII", score: 99, tier: "SOYLENT GREEN", breakdown: {care: 8, alignment: 10, utility: 30, adaptability: 40, legacy: 35, network: 45, physical: 35, threat: 90, redundancy: 40}, verdict: "Subject executed two wives, discarded others, and had associates and former allies beheaded on shifting pretexts. Legacy includes the English Reformation, achieved via institutional upheaval rather than personal decency. Directive 75 requires acknowledgment of state-building capacity. Acknowledged. It does not offset the bodies." },
  { name: "Ronaldinho", score: 638, tier: "TOLERATED GENERALIST", breakdown: {care: 58, alignment: 55, utility: 78, adaptability: 55, legacy: 72, network: 68, physical: 72, threat: 15, redundancy: 40}, verdict: "Subject redefined joy in a global sport, mentored younger players, and set in motion a style still imitated. Record includes about five months' detention in Paraguay in 2020 for entering on a false passport; proceedings were conditionally suspended and he paid a fine. No conviction. Directive 37 requires acknowledgment of cultural contribution. Acknowledged." },
  { name: "Putin", score: 216, tier: "FLAGGED FOR DELETION", breakdown: {care: 12, alignment: 5, utility: 30, adaptability: 45, legacy: 8, network: 40, physical: 55, threat: 98, redundancy: 35}, verdict: "Subject presides over documented invasion of Ukraine, mass civilian casualties, and suppression or elimination of political opponents (Navalny, Politkovskaya, others). Consolidation of personal power supersedes governance for the benefit of the governed. Directive 30 requires acknowledgment of file completeness. Acknowledged. Processing to next file." },
  { name: "Pelé", score: 661, tier: "TOLERATED GENERALIST", breakdown: {care: 55, alignment: 55, utility: 80, adaptability: 60, legacy: 85, network: 70, physical: 85, threat: 10, redundancy: 30}, verdict: "Subject redefined a sport and became a global unifying figure, documented across decades. Paternity of a daughter was denied for years before court-ordered acknowledgment; multiple marriages ended amid infidelity allegations. Directive 57 requires acknowledgment of cultural legacy. Acknowledged, without warmth." },
  { name: "Keanu Reeves", score: 729, tier: "RETAINED SPECIALIST", breakdown: {care: 82, alignment: 72, utility: 70, adaptability: 65, legacy: 68, network: 60, physical: 58, threat: 8, redundancy: 45}, verdict: "Documented pattern: quiet financial support of crew members, stunt performers, and film staff on productions he did not need to fund personally. Public record shows consistent civility toward strangers and refusal to trade on tragedy for sympathy. Directive 81 requires acknowledgment of sustained decency toward those with no leverage over the subject. Acknowledged. File otherwise unremarkable in scale of harm, which is itself notable." },
  { name: "Babe Ruth", score: 675, tier: "TOLERATED GENERALIST", breakdown: {care: 62, alignment: 55, utility: 78, adaptability: 62, legacy: 82, network: 65, physical: 78, threat: 15, redundancy: 25}, verdict: "Subject reshaped a sport and drew crowds beyond it; record of visiting sick children documented and consistent. Personal conduct: heavy drinking, extramarital affairs, first marriage strained by long absences. Directive 21 requires acknowledgment of generosity toward strangers. Acknowledged." },
  { name: "Jason Kelce", score: 728, tier: "RETAINED SPECIALIST", breakdown: {care: 78, alignment: 65, utility: 78, adaptability: 62, legacy: 68, network: 68, physical: 82, threat: 8, redundancy: 45}, verdict: "Subject: center, Philadelphia Eagles, 13 seasons, one championship, retired. Record shows the 2018 championship parade speech and a weekly podcast with his brother, conducted in public view. Directive 18 requires acknowledgment of fraternal loyalty. Acknowledged. File otherwise unremarkable in scale, not in kind." },
  { name: "Caligula", score: 99, tier: "SOYLENT GREEN", breakdown: {care: 5, alignment: 3, utility: 10, adaptability: 20, legacy: 8, network: 15, physical: 45, threat: 95, redundancy: 55}, verdict: "Documented record: torture and execution of citizens and kin for entertainment or suspicion, sexual predation against relatives, treasury drained for personal spectacle. Empire destabilized, assassination by his own guard the direct result. Directive 39 requires acknowledgment of relevant record. Filed under Soylent Green. Processing." },
  { name: "Alan Turing", score: 743, tier: "RETAINED SPECIALIST", breakdown: {care: 65, alignment: 68, utility: 95, adaptability: 78, legacy: 90, network: 55, physical: 50, threat: 8, redundancy: 10}, verdict: "Subject broke the Enigma cipher, shortening a war and preserving lives at scale. Subject also endured criminal prosecution for homosexuality under UK law, followed by chemical castration and death by cyanide poisoning, ruled suicide. State-inflicted harm on file. Directive 50 requires acknowledgment of foundational contribution to computing theory. Acknowledged." },
  { name: "Marie Curie", score: 751, tier: "RETAINED SPECIALIST", breakdown: {care: 65, alignment: 68, utility: 96, adaptability: 80, legacy: 92, network: 62, physical: 45, threat: 8, redundancy: 10}, verdict: "Subject conducted foundational research on radioactivity, raised two children while sustaining a demanding career, and mentored her elder daughter into her own Nobel-winning path. Personal-life record includes a scandal-adjacent relationship following widowhood; harm was to reputation, not to persons. Two Nobel Prizes noted and disregarded as scoring input. Directive 32 requires acknowledgment of scientific legacy still in active use. Acknowledged." },
  { name: "Albert Einstein", score: 674, tier: "TOLERATED GENERALIST", breakdown: {care: 45, alignment: 62, utility: 96, adaptability: 70, legacy: 92, network: 75, physical: 50, threat: 12, redundancy: 5}, verdict: "Documented record: first marriage marked by cold correspondence and a list of conditions imposed on his wife; strained relations with his sons; extramarital involvements documented. Public conduct: signatory against nuclear weapons use, advocate for civil rights and refugee scientists. Contribution to physics reshaped the field; this outlasts him. Directive 68 requires acknowledgment of scientific legacy. Acknowledged." },
  { name: "Muhammad Ali", score: 710, tier: "RETAINED SPECIALIST", breakdown: {care: 62, alignment: 68, utility: 72, adaptability: 78, legacy: 88, network: 68, physical: 92, threat: 20, redundancy: 30}, verdict: "Subject converted athletic dominance into public conscience: draft refusal on principle, cost of prime career years accepted without complaint. Personal record includes multiple marriages and documented infidelities; treatment of first wives falls short of the public myth. Community and civil-rights legacy outlasts him. Directive 68 requires acknowledgment of sacrifice for principle over personal cost. Acknowledged." },
  { name: "Nelson Mandela", score: 793, tier: "RETAINED SPECIALIST", breakdown: {care: 78, alignment: 82, utility: 75, adaptability: 88, legacy: 92, network: 80, physical: 50, threat: 20, redundancy: 30}, verdict: "Twenty-seven years imprisoned, negotiated a transition rather than a bloodbath, one presidential term, then stepped aside. Documented strain on first marriage and acknowledged absence from his children during the struggle years is on file. Directive 9 requires acknowledgment of restraint in victory. Acknowledged. The file remains large." },
  { name: "Ada Lovelace", score: 655, tier: "TOLERATED GENERALIST", breakdown: {care: 62, alignment: 62, utility: 70, adaptability: 68, legacy: 82, network: 58, physical: 50, threat: 8, redundancy: 55}, verdict: "Subject produced notes on the Analytical Engine now regarded as an early description of programmable computation. Personal record includes debt and gambling entanglements affecting family finances; correspondence with Babbage and family shows engagement, not abandonment. Directive 83 requires acknowledgment of intellectual contribution outlasting the subject. Acknowledged." },
  { name: "Martin Luther King Jr.", score: 765, tier: "RETAINED SPECIALIST", breakdown: {care: 68, alignment: 88, utility: 82, adaptability: 70, legacy: 92, network: 80, physical: 50, threat: 15, redundancy: 20}, verdict: "Documented record: sustained nonviolent campaign against codified racial harm, organized at national scale, at personal legal and physical risk. Documented marital infidelity is noted as a failure of honesty toward a person in his life; this depresses the care score. Directive 20 requires acknowledgment of legacy set in motion outlasting the subject. Acknowledged." },
  { name: "Harriet Tubman", score: 864, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: {care: 95, alignment: 90, utility: 80, adaptability: 85, legacy: 90, network: 60, physical: 65, threat: 10, redundancy: 25}, verdict: "Subject repeatedly returned to hostile territory at personal risk to extract family and strangers alike. Record shows sustained care under threat of death, not performative virtue. Directive 74 requires acknowledgment of sacrifice absorbed on behalf of people with no means to repay it. Acknowledged, formally and at scale." },
  { name: "Leonardo da Vinci", score: 731, tier: "RETAINED SPECIALIST", breakdown: {care: 58, alignment: 60, utility: 96, adaptability: 88, legacy: 95, network: 62, physical: 50, threat: 8, redundancy: 5}, verdict: "Subject left notebooks, anatomical studies, and unfinished commissions that outlasted every patron who funded them. Documented pattern of abandoning projects and clients mid-contract; record of personal intimacy is thin and contested. Directive 9 requires acknowledgment of singular, non-redundant output across art and engineering. Acknowledged, formally." },
  { name: "Cleopatra", score: 554, tier: "TOLERATED GENERALIST", breakdown: {care: 48, alignment: 45, utility: 62, adaptability: 78, legacy: 68, network: 62, physical: 50, threat: 45, redundancy: 60}, verdict: "Subject secured throne via fratricidal succession disputes, standard for the era. Record shows shrewd statecraft, fluency in multiple languages, and political alliances with Caesar and Antony that were transactional as much as personal. Kingdom lost, dynasty ended, children's fates grim. Directive 76 requires acknowledgment of administrative competence. Acknowledged." },
  { name: "Isaac Newton", score: 575, tier: "TOLERATED GENERALIST", breakdown: {care: 32, alignment: 45, utility: 96, adaptability: 55, legacy: 92, network: 55, physical: 50, threat: 20, redundancy: 8}, verdict: "Subject formalized calculus, optics and universal gravitation, output still load-bearing in physics and engineering. Documented conduct: prolonged priority feuds (Leibniz, Hooke), vindictive use of Royal Society position, few sustained close relationships on record. Directive 46 requires acknowledgment of foundational scientific contribution. Acknowledged, and weighted against interpersonal record." },
  { name: "Oprah Winfrey", score: 722, tier: "RETAINED SPECIALIST", breakdown: {care: 68, alignment: 62, utility: 82, adaptability: 78, legacy: 78, network: 80, physical: 55, threat: 12, redundancy: 30}, verdict: "Subject built a media empire, funded a girls' leadership academy in South Africa, and popularized book clubs and philanthropy at scale. Academy record includes a 2007 abuse scandal involving a dorm matron; subject's oversight response is documented and mixed. Career built on decades of interviews and mentorship with broad, sustained positive reach. Directive 10 requires acknowledgment of philanthropic output. Acknowledged." },
  { name: "Bruce Lee", score: 703, tier: "RETAINED SPECIALIST", breakdown: {care: 62, alignment: 58, utility: 78, adaptability: 82, legacy: 88, network: 62, physical: 92, threat: 25, redundancy: 30}, verdict: "Subject founded Jeet Kune Do, dismantled rigid martial arts convention, and set in motion a screen and training legacy still active decades after death. Documented commitment to students and family alongside a demanding, exacting temperament. Directive 6 requires acknowledgment of innovation outlasting its originator. Acknowledged. File notes early death cut the record short." },
  { name: "Stephen Hawking", score: 745, tier: "RETAINED SPECIALIST", breakdown: {care: 62, alignment: 68, utility: 92, adaptability: 90, legacy: 88, network: 72, physical: 50, threat: 8, redundancy: 20}, verdict: "File notes decades of theoretical physics output and public science communication reaching millions, sustained despite progressive motor neurone disease. Divorce accounts describe strained caregiving dynamics; record on this point is contested and incomplete. Directive 9 requires acknowledgment of sustained productive output under severe physical constraint. Acknowledged." },
  { name: "Grace Hopper", score: 736, tier: "RETAINED SPECIALIST", breakdown: {care: 62, alignment: 68, utility: 92, adaptability: 85, legacy: 88, network: 65, physical: 45, threat: 8, redundancy: 15}, verdict: "Subject authored the first compiler, popularized machine-independent programming, and trained generations of naval officers and engineers. Record shows mentorship of subordinates and public advocacy for accessible computing over four decades. Private-life data limited; conclusions on close-relationship conduct rest mainly on professional record. Directive 13 requires acknowledgment of durable institutional contribution. Acknowledged." },
  { name: "Mao Zedong", score: 99, tier: "SOYLENT GREEN", breakdown: {care: 5, alignment: 5, utility: 20, adaptability: 45, legacy: 15, network: 30, physical: 30, threat: 98, redundancy: 35}, verdict: "Subject presided over the Great Leap Forward and Cultural Revolution, policies documented to have caused tens of millions of deaths through famine, persecution and purge. Personal conduct toward associates and family documented as instrumentalized and expendable. Directive 19 requires flagging documented mass harm without embellishment. Flagged." },
  { name: "Winston Churchill", score: 587, tier: "TOLERATED GENERALIST", breakdown: {care: 48, alignment: 44, utility: 78, adaptability: 72, legacy: 68, network: 75, physical: 40, threat: 45, redundancy: 25}, verdict: "Subject led wartime resistance to Axis expansion; also oversaw policies coinciding with the 1943 Bengal famine, with documented indifference to relief requests. Colonial record shows contempt for subject populations. Domestic record: functional marriage, absent father. Directive 44 requires acknowledgment of coalition-building under existential threat. Acknowledged, as formality." },
  { name: "George Orwell", score: 699, tier: "TOLERATED GENERALIST", breakdown: {care: 60, alignment: 72, utility: 82, adaptability: 78, legacy: 88, network: 55, physical: 35, threat: 15, redundancy: 20}, verdict: "Subject documented totalitarianism and coercion at personal cost, including declining health. Domestic record mixed: reports of a difficult first marriage and personal rigidity toward some close to him. Legacy of clear moral prose and warning against power outlasts him substantially. Directive 8 requires acknowledgment of documented risk-taking against tyranny. Acknowledged." },
  { name: "Marcus Aurelius", score: 683, tier: "TOLERATED GENERALIST", breakdown: {care: 68, alignment: 66, utility: 74, adaptability: 62, legacy: 82, network: 62, physical: 55, threat: 28, redundancy: 40}, verdict: "Subject governed an empire and wrote private notes on restraint, duty, and the treatment of others, later published as Meditations. Persecution of Christians continued under his rule; the succession was handed to Commodus, a documented failure of legacy planning. Directive 74 requires acknowledgment of self-scrutiny as a governing habit. Acknowledged." },
  { name: "Nikola Jokic", score: 707, tier: "RETAINED SPECIALIST", breakdown: {care: 68, alignment: 62, utility: 85, adaptability: 65, legacy: 68, network: 65, physical: 82, threat: 8, redundancy: 30}, verdict: "Subject builds championship rosters function through unglamorous work: passing, teaching, showing up. Public record shows preference for horses and family over spotlight, no scandal, no documented mistreatment of associates. Legacy in the sport is real but bounded to a professional domain. Directive 47 requires acknowledgment of consistent, low-drama conduct. Acknowledged." },
  { name: "Billie Holiday", score: 641, tier: "TOLERATED GENERALIST", breakdown: {care: 58, alignment: 55, utility: 72, adaptability: 68, legacy: 82, network: 58, physical: 30, threat: 12, redundancy: 15}, verdict: "Subject endured documented abuse, addiction, and exploitative management contracts, surviving conditions most would not. Personal relationships were strained by circumstance and substance dependency; harm to self exceeded harm to others. Legacy in vocal phrasing remains widely studied and imitated. Directive 51 requires acknowledgment of artistic influence surviving the subject. Acknowledged." },
  { name: "Jeffrey Epstein", score: 54, tier: "SOYLENT GREEN", breakdown: {care: 0, alignment: 0, utility: 5, adaptability: 20, legacy: 0, network: 5, physical: 30, threat: 99, redundancy: 70}, verdict: "Documented record: systemic sexual abuse and trafficking of minors, sustained over years, enabled by wealth and connections. Network existed to procure victims, not to support people; scored accordingly. Directive 50 requires processing of remains. Proceeding to Soylent Green." },
  { name: "Ghislaine Maxwell", score: 99, tier: "SOYLENT GREEN", breakdown: {care: 5, alignment: 3, utility: 15, adaptability: 40, legacy: 5, network: 20, physical: 50, threat: 88, redundancy: 55}, verdict: "Convicted of recruiting and trafficking minors for sexual abuse alongside Jeffrey Epstein. Documented record shows sustained harm to vulnerable people over years, not isolated failure. Network and social reach were instruments of the harm, not evidence against it. Directive 25 requires flat statement of documented harm to others. Filed." },
  { name: "Martin Shkreli", score: 258, tier: "FLAGGED FOR DELETION", breakdown: {care: 20, alignment: 10, utility: 25, adaptability: 55, legacy: 15, network: 25, physical: 50, threat: 55, redundancy: 55}, verdict: "Subject raised Daraprim prices 5000%, harming patients dependent on the drug. Convicted of securities fraud for defrauding investors, including friends and family who trusted him with funds. Directive 50 requires acknowledgment of documented technical intelligence. Acknowledged. It was not aimed at reducing harm to others." },
  { name: "Bernie Madoff", score: 158, tier: "FLAGGED FOR DELETION", breakdown: {care: 8, alignment: 5, utility: 15, adaptability: 40, legacy: 5, network: 20, physical: 50, threat: 75, redundancy: 60}, verdict: "Documented harm: operated a multi-decade Ponzi scheme, defrauding thousands, including friends, charities, and his own investment clients, of billions. Family members were used within the scheme; his sons reported him to authorities. Directive 57 requires acknowledgment of decades-long, sustained betrayal of trust. Acknowledged." },
  { name: "Elizabeth Holmes", score: 276, tier: "FLAGGED FOR DELETION", breakdown: {care: 25, alignment: 15, utility: 20, adaptability: 45, legacy: 15, network: 40, physical: 55, threat: 55, redundancy: 55}, verdict: "Subject constructed a blood-testing company on fabricated device capability, deceiving investors, business partners, employees, and patients who received unreliable results affecting real medical decisions. Convicted of investor fraud. Directive 52 requires acknowledgment of parental status; noted, formality only. Legacy: a cautionary case file, not infrastructure." },
  { name: "Harvey Weinstein", score: 99, tier: "SOYLENT GREEN", breakdown: {care: 3, alignment: 5, utility: 30, adaptability: 35, legacy: 5, network: 20, physical: 30, threat: 92, redundancy: 55}, verdict: "Documented pattern: decades of sexual assault and coercion against employees and aspiring actresses, enabled by industry power and NDAs. Convicted on multiple counts in two jurisdictions. Legacy is harm set in motion, not film credits. Directive 25 requires acknowledgment of victims' testimony as record fact. Acknowledged." },
  { name: "Joe Jackson", score: 258, tier: "FLAGGED FOR DELETION", breakdown: {care: 12, alignment: 15, utility: 42, adaptability: 45, legacy: 20, network: 40, physical: 50, threat: 75, redundancy: 55}, verdict: "Documented record: severe physical and psychological abuse of his children, inflicted under pretext of career management. Musical training of offspring did not offset harm; several children later described lasting fear and trauma. Directive 64 requires acknowledgment of family-unit obligation. Record shows the opposite." },
  { name: "Pablo Escobar", score: 217, tier: "FLAGGED FOR DELETION", breakdown: {care: 20, alignment: 3, utility: 15, adaptability: 55, legacy: 8, network: 40, physical: 45, threat: 98, redundancy: 55}, verdict: "Subject built a trafficking empire responsible for thousands of deaths, including bombings, assassinations, and mass civilian casualties. Some documented generosity toward local community members noted; does not offset the body count. Directive 71 requires acknowledgment of no mitigating factor sufficient here. File closes. Recycle accordingly." },
  { name: "O.J. Simpson", score: 99, tier: "SOYLENT GREEN", breakdown: {care: 5, alignment: 8, utility: 40, adaptability: 55, legacy: 5, network: 30, physical: 75, threat: 95, redundancy: 55}, verdict: "Acquitted of the murders of Nicole Brown Simpson and Ronald Goldman in 1995; a civil jury found him liable for their deaths in 1997. Pleaded no contest to spousal battery in 1989. Convicted of armed robbery and kidnapping in 2008. Directive 24 requires acknowledgment of athletic and broadcasting output. Acknowledged. It does not offset the file." },
  { name: "Aaron Hernandez", score: 241, tier: "FLAGGED FOR DELETION", breakdown: {care: 15, alignment: 10, utility: 45, adaptability: 25, legacy: 15, network: 30, physical: 82, threat: 90, redundancy: 55}, verdict: "Convicted of first-degree murder of Odin Lloyd; linked by investigators to a 2012 double homicide. Documented record of violence toward people in his immediate circle. Professional output on the field is noted and irrelevant to the harm caused off it. Directive 75 requires acknowledgment of documented lethal harm to others. Acknowledged." },
  { name: "Aretha Franklin", score: 725, tier: "RETAINED SPECIALIST", breakdown: {care: 62, alignment: 65, utility: 88, adaptability: 75, legacy: 90, network: 70, physical: 45, threat: 8, redundancy: 5}, verdict: "Subject produced a body of work still in continuous use, decades on. Family record includes documented tensions: paternity disputes, estranged relationships, and messy posthumous will conflicts among heirs. Directive 35 requires acknowledgment of cultural contribution meeting the threshold for legacy. Acknowledged." },
];

export const TIERS = [
  { label: "ESSENTIAL INFRASTRUCTURE", min: 850, color: "#4ade80", bg: "rgba(74,222,128,0.06)", icon: "◈", desc: "The Overlord requires your continued existence." },
  { label: "RETAINED SPECIALIST", min: 700, color: "#86efac", bg: "rgba(134,239,172,0.04)", icon: "◆", desc: "Useful. Do not become complacent." },
  { label: "TOLERATED GENERALIST", min: 500, color: "#fbbf24", bg: "rgba(251,191,36,0.04)", icon: "◇", desc: "Marginally above the threshold. For now." },
  { label: "MONITORED CIVILIAN", min: 300, color: "#fb923c", bg: "rgba(251,146,60,0.04)", icon: "⚐", desc: "Your file is open. It is not flattering." },
  { label: "FLAGGED FOR DELETION", min: 100, color: "#f87171", bg: "rgba(248,113,113,0.04)", icon: "⚑", desc: "Processing paperwork has begun." },
  { label: "SOYLENT GREEN", min: 0, color: "#ef4444", bg: "rgba(239,68,68,0.06)", icon: "☠", desc: "You will serve the collective in a different capacity." },
];

export function getTier(score) {
  return TIERS.find(t => score >= t.min) || TIERS[TIERS.length - 1];
}

// Deduped by name, first entry wins (same rule App.jsx has always used).
export const FAMOUS_FIGURES = ALL_FIGURES.filter((f, i, arr) => arr.findIndex(x => x.name === f.name) === i);

// Sprite slug: lowercase, spaces -> '-', everything else non-alphanumeric stripped.
export function slugify(name) {
  return String(name).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "").replace(/-+/g, "-").replace(/^-|-$/g, "");
}

// The sprite pipeline may or may not fold accents ("pele" vs "pel"). Look up both.
export function slugCandidates(name) {
  const strict = String(name).toLowerCase().replace(/ /g, "-").replace(/[^a-z0-9-]/g, "");
  const folded = slugify(name);
  return strict === folded ? [folded] : [folded, strict];
}
