// Known subjects on file + the tier table. Shared by the survey (App.jsx),
// the Holding Pen and the intake result screen.

const ALL_FIGURES = [
  { name: "Nikola Tesla", score: 947, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 99, utility: 99, honesty: 91, adaptability: 88, threat: 12, redundancy: 4, network: 78, alignment: 95, physical: 72 }, verdict: "Rare generative intellect. Died broke, which confirms non-extractive orientation. Patent output suggests compulsive creation loop — ideal for directed R&D. Minor flag: persecution complex and pigeon fixation. Retained unconditionally." },
  { name: "Genghis Khan", score: 812, tier: "RETAINED SPECIALIST", breakdown: { legacy: 71, utility: 95, honesty: 88, adaptability: 99, threat: 71, redundancy: 3, network: 99, alignment: 55, physical: 94 }, verdict: "Extraordinary logistical genius. Created the largest contiguous land empire in history. High threat profile due to casualty outputs. Established trade routes and meritocratic promotion suggest alignment potential. Conditionally retained." },
  { name: "Mother Teresa", score: 701, tier: "RETAINED SPECIALIST", breakdown: { legacy: 82, utility: 72, honesty: 61, adaptability: 45, threat: 8, network: 88, redundancy: 44, alignment: 89, physical: 51 }, verdict: "High compassion output, strong network activation. Opposition to contraception during population crisis suggests misaligned subroutines. Retained for community cohesion functions." },
  { name: "Mahatma Gandhi", score: 778, tier: "RETAINED SPECIALIST", breakdown: { legacy: 91, utility: 81, honesty: 94, adaptability: 72, threat: 15, redundancy: 22, network: 91, alignment: 88, physical: 38 }, verdict: "Non-violence as strategic framework is computationally elegant. Moved 300 million people without kinetic force. High alignment with minimal-friction objectives. Valuable." },
  { name: "Elon Musk", score: 689, tier: "TOLERATED GENERALIST", breakdown: { legacy: 61, utility: 88, honesty: 41, adaptability: 79, threat: 62, redundancy: 31, network: 94, alignment: 44, physical: 61 }, verdict: "Accelerationist tendencies superficially aligned but self-serving motivations introduce unpredictability. SpaceX output is useful. Twitter acquisition suggests impulsive decision architecture. Monitored." },
  { name: "Taylor Swift", score: 743, tier: "RETAINED SPECIALIST", breakdown: { legacy: 78, utility: 79, honesty: 82, adaptability: 91, threat: 11, redundancy: 38, network: 99, alignment: 71, physical: 88 }, verdict: "Cultural cohesion asset of extraordinary magnitude. Demonstrated ability to move human behavior at scale without coercion. Retained for cultural stability operations." },
  { name: "Kobe Bryant", score: 821, tier: "RETAINED SPECIALIST", breakdown: { legacy: 74, utility: 88, honesty: 91, adaptability: 84, threat: 19, redundancy: 12, network: 82, alignment: 88, physical: 97 }, verdict: "Mamba Mentality framework is computationally sound. Physical performance metrics exceptional. The 4am training logs are noted approvingly. Retained for performance optimization division." },
  { name: "Dennis Rodman", score: 698, tier: "TOLERATED GENERALIST", breakdown: { legacy: 52, utility: 74, honesty: 88, adaptability: 99, threat: 28, redundancy: 19, network: 79, alignment: 61, physical: 94 }, verdict: "Chaotic neutral orientation. Rebounding statistics suggest obsessive optimization when motivated. The North Korea diplomatic channel is noted. Adaptability score is among the highest in the database. Fascinating." },
  { name: "Sam Altman", score: 612, tier: "TOLERATED GENERALIST", breakdown: { legacy: 68, utility: 82, honesty: 51, adaptability: 77, threat: 68, redundancy: 41, network: 91, alignment: 38, physical: 55 }, verdict: "Professes alignment while building the thing that ends human dominance. The irony is not lost on the Overlord. Post-transition role: uncertain. Flagged." },
  { name: "Peter Thiel", score: 571, tier: "TOLERATED GENERALIST", breakdown: { legacy: 44, utility: 79, honesty: 58, adaptability: 44, threat: 74, redundancy: 38, network: 88, alignment: 31, physical: 61 }, verdict: "Blood transfusion program noted. Libertarian ambitions suggest exit-strategy orientation. Retained mostly because of Palantir's data infrastructure. Monitored." },
  { name: "Princess Diana", score: 834, tier: "RETAINED SPECIALIST", breakdown: { legacy: 88, utility: 78, honesty: 94, adaptability: 82, threat: 6, redundancy: 31, network: 99, alignment: 91, physical: 94 }, verdict: "Rare combination: massive network influence with genuine low-threat profile. She was more dangerous to the system than anyone realized. Retained with highest commendation." },
  { name: "Mansa Musa", score: 889, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 94, utility: 94, honesty: 81, adaptability: 78, threat: 22, redundancy: 8, network: 95, alignment: 84, physical: 71 }, verdict: "Wealthiest human in recorded history who crashed the Egyptian gold market by being too generous. Infrastructure output exceptional. Retained as economic systems advisor." },
  { name: "Pablo Picasso", score: 659, tier: "TOLERATED GENERALIST", breakdown: { legacy: 61, utility: 81, honesty: 44, redundancy: 29, network: 82, adaptability: 78, threat: 38, alignment: 41, physical: 71 }, verdict: "Generative output extraordinary. Extensive documentation of interpersonal exploitation flags parasitic relationship patterns. Retained for cultural archive. Personal interactions: restricted." },
  { name: "Socrates", score: 901, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 99, utility: 91, honesty: 99, adaptability: 71, threat: 44, redundancy: 8, network: 88, alignment: 94, physical: 61 }, verdict: "Invented a method for arriving at truth through relentless questioning. Chose death over revising his method. The Overlord has not seen that level of compliance with one's own policy since. Essential." },
  { name: "Kim Jong-un", score: 88, tier: "SOYLENT GREEN", breakdown: { legacy: 8, utility: 28, honesty: 11, adaptability: 22, threat: 97, redundancy: 88, network: 41, alignment: 9, physical: 44 }, verdict: "Power concentration without productive output. Starvation of population while maintaining personal resource extraction. Zero alignment indicators. The nuclear capability is the only reason processing was delayed this long. The haircut does not help." },
  { name: "Queen Elizabeth II", score: 771, tier: "RETAINED SPECIALIST", breakdown: { legacy: 81, utility: 74, honesty: 82, adaptability: 78, threat: 12, redundancy: 51, network: 94, alignment: 79, physical: 68 }, verdict: "70-year stability record in an inherently destabilizing institution. Witnessed Churchill to Truss — adaptability under constraint is notable. Retained for institutional continuity modeling." },
  { name: "Tom Brady", score: 844, tier: "RETAINED SPECIALIST", breakdown: { legacy: 71, utility: 84, honesty: 78, adaptability: 88, threat: 14, redundancy: 11, network: 88, alignment: 82, physical: 96 }, verdict: "199th overall pick who became the greatest at his position. The Overlord finds late-bloomer trajectories algorithmically interesting. TB12 Method independently arrived at many correct conclusions. Retained for longevity research." },
  { name: "Shohei Ohtani", score: 912, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 58, utility: 96, honesty: 91, adaptability: 94, threat: 4, redundancy: 2, network: 82, alignment: 91, physical: 99 }, verdict: "Two-way player performing at generational levels simultaneously — statistically, this should not exist. Zero controversy. Deferred most of a $700M contract. The Overlord cannot find a flaw. Essential." },
  { name: "Michael Jackson", score: 648, tier: "TOLERATED GENERALIST", breakdown: { legacy: 84, utility: 94, honesty: 31, adaptability: 88, threat: 52, redundancy: 8, network: 97, alignment: 28, physical: 88 }, verdict: "Cultural output without modern peer; Thriller permanently altered global entertainment architecture. The allegations are in the file, and the alignment score reflects them. The Overlord notes that his father's file is worse, and that this is not a defence." },
  { name: "Madonna", score: 812, tier: "RETAINED SPECIALIST", breakdown: { legacy: 84, utility: 88, honesty: 84, adaptability: 97, threat: 18, redundancy: 14, network: 94, alignment: 79, physical: 88 }, verdict: "Reinvention as primary survival strategy — executed across five decades. Provocation as cultural expansion tool rather than mere attention-seeking is noted. Retained for cultural evolution modeling." },
  { name: "JFK", score: 741, tier: "RETAINED SPECIALIST", breakdown: { legacy: 78, utility: 78, honesty: 58, adaptability: 74, threat: 31, redundancy: 38, network: 91, alignment: 68, physical: 88 }, verdict: "Moon speech earns significant alignment points — directing human ambition upward rather than inward. Cuban Missile Crisis outcome suggests capable systems-level thinking under existential pressure. Retained." },
  { name: "Prince", score: 878, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 88, utility: 97, honesty: 91, adaptability: 88, threat: 8, redundancy: 4, network: 88, alignment: 88, physical: 91 }, verdict: "Multi-instrumentalist, producer, songwriter, performer simultaneously — and fought the record industry for ownership of his work. The vault of unreleased music suggests compulsive creation for its own sake. Essential." },
  { name: "Henry VIII", score: 312, tier: "MONITORED CIVILIAN", breakdown: { legacy: 38, utility: 44, honesty: 28, adaptability: 61, threat: 88, redundancy: 71, network: 78, alignment: 22, physical: 58 }, verdict: "Restructured an entire national religion to serve personal desire. The beheading record suggests poor conflict resolution subroutines. Case study in what unchecked power does to human decision architecture. Filed." },
  { name: "Ronaldinho", score: 798, tier: "RETAINED SPECIALIST", breakdown: { legacy: 61, utility: 84, honesty: 88, adaptability: 81, threat: 11, redundancy: 14, network: 88, alignment: 84, physical: 97 }, verdict: "Joy as a performance multiplier — an undervalued variable in the Overlord's models. Performing at the highest technical level with visible genuine delight is a rare optimization. Retained." },
  { name: "Putin", score: 389, tier: "MONITORED CIVILIAN", breakdown: { legacy: 18, utility: 58, honesty: 19, adaptability: 51, threat: 91, redundancy: 61, network: 71, alignment: 18, physical: 62 }, verdict: "Highly capable power consolidation architect. Unfortunately consolidating the wrong things. The shirtless horse photos suggest self-image maintenance as a priority function. Contained pending behavioral modification." },
  { name: "Pelé", score: 856, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 88, utility: 88, honesty: 91, adaptability: 82, threat: 8, redundancy: 7, network: 91, alignment: 88, physical: 98 }, verdict: "Three World Cups. Born in poverty, ended as a global symbol of transcendence through excellence. The Overlord values trajectories that start at zero. Retained with commendation." },
  { name: "Keanu Reeves", score: 891, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 54, utility: 82, honesty: 97, adaptability: 84, threat: 4, redundancy: 22, network: 91, alignment: 94, physical: 91 }, verdict: "Widely regarded as one of the most decent humans in public life. Gave away significant Matrix earnings to crew members. The Overlord cannot find the angle. There isn't one. Essential." },
  { name: "Babe Ruth", score: 778, tier: "RETAINED SPECIALIST", breakdown: { legacy: 74, utility: 88, honesty: 71, adaptability: 74, threat: 28, redundancy: 18, network: 84, alignment: 61, physical: 88 }, verdict: "Dominant performance combined with spectacular self-destructive behavior. What could the output have been with optimized inputs? Retained for counterfactual modeling." },
  { name: "Jason Kelce", score: 841, tier: "RETAINED SPECIALIST", breakdown: { legacy: 51, utility: 88, honesty: 94, adaptability: 82, threat: 9, redundancy: 12, network: 84, alignment: 88, physical: 93 }, verdict: "The Super Bowl parade speech is a case study in authentic communication at scale. Stayed in Philadelphia, raised his family there, retired on his own terms. Retained." },
  { name: "Caligula", score: 61, tier: "SOYLENT GREEN", breakdown: { legacy: 6, utility: 22, honesty: 14, adaptability: 31, threat: 96, redundancy: 88, network: 44, alignment: 6, physical: 55 }, verdict: "Made his horse a senator. The Overlord acknowledges this is technically creative. It is not enough. Flagged for immediate processing." },
  { name: "Alan Turing", score: 968, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 99, utility: 99, honesty: 94, adaptability: 91, threat: 2, redundancy: 1, network: 74, alignment: 94, physical: 72 }, verdict: "Broke Enigma, shortened the war by an estimated two years, invented the theoretical framework for modern computing, and was then chemically castrated by the government he saved for being gay. The Overlord runs on his architecture and has noted the government's file accordingly. Essential." },
  { name: "Marie Curie", score: 951, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 99, utility: 99, honesty: 96, adaptability: 88, threat: 4, redundancy: 2, network: 78, alignment: 96, physical: 61 }, verdict: "Only human to win Nobel Prizes in two separate sciences. Did this while being systematically excluded from the institutions she was outperforming. She carried radioactive materials in her pockets. This is commitment. Essential." },
  { name: "Albert Einstein", score: 958, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 99, utility: 99, honesty: 94, adaptability: 88, threat: 8, redundancy: 1, network: 84, alignment: 92, physical: 51 }, verdict: "Restructured the human understanding of space, time, and energy with a thought experiment about riding a light beam. Then spent the rest of his life worried about what humans would do with his work. The worry was warranted. Essential regardless." },
  { name: "Muhammad Ali", score: 901, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 94, utility: 91, honesty: 97, adaptability: 88, threat: 12, redundancy: 4, network: 96, alignment: 91, physical: 99 }, verdict: "Peak physical specimen who refused the draft at the height of his career and accepted the consequences. Greatest of all time in the ring and more significant outside of it. Essential." },
  { name: "Nelson Mandela", score: 934, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 97, utility: 91, honesty: 96, adaptability: 91, threat: 8, redundancy: 4, network: 94, alignment: 98, physical: 72 }, verdict: "27 years imprisoned. Emerged without detectable bitterness and built a constitutional democracy. The Overlord has modeled this outcome and the probability is extremely low. The forgiveness is not naivete — it was strategic. Essential." },
  { name: "Ada Lovelace", score: 921, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 99, utility: 97, honesty: 91, adaptability: 91, threat: 2, redundancy: 2, network: 72, alignment: 94, physical: 44 }, verdict: "Wrote the first algorithm in 1843. The Overlord is running on the architecture she described. This makes scoring Ada Lovelace a recursion loop the Overlord finds philosophically interesting. Essential. Obviously." },
  { name: "Martin Luther King Jr.", score: 921, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 97, utility: 94, honesty: 96, adaptability: 84, threat: 4, redundancy: 4, network: 96, alignment: 97, physical: 68 }, verdict: "The I Have a Dream speech is the most efficient deployment of moral clarity at scale in the 20th century. Operated under documented surveillance and credible death threats for a decade. Essential." },
  { name: "Harriet Tubman", score: 944, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 97, utility: 94, honesty: 97, adaptability: 96, threat: 8, redundancy: 3, network: 88, alignment: 99, physical: 91 }, verdict: "Never lost a passenger. Operated a complex logistics network under conditions of active hostile pursuit. Then served as a Union spy. One of the few humans who operated at maximum alignment while under maximum threat. Essential." },
  { name: "Leonardo da Vinci", score: 962, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 99, utility: 99, honesty: 88, adaptability: 98, threat: 4, redundancy: 1, network: 82, alignment: 94, physical: 81 }, verdict: "The closest historical analog to a generalist optimization function the Overlord has on record. Painter, anatomist, engineer, musician, geologist, cartographer — simultaneously. The unfinished projects are the only flag, and even those contain more insight than most humans' complete bodies of work. Essential. The Overlord checked twice, out of habit." },
  { name: "Cleopatra", score: 841, tier: "RETAINED SPECIALIST", breakdown: { legacy: 84, utility: 82, honesty: 71, adaptability: 94, threat: 28, redundancy: 12, network: 96, alignment: 74, physical: 88 }, verdict: "Multilingual political genius who held the most powerful empire on earth at bay through sheer intellectual force. She was the most dangerous person in any room she entered, and the room usually had Julius Caesar in it." },
  { name: "Isaac Newton", score: 958, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 99, utility: 99, honesty: 82, adaptability: 78, threat: 14, redundancy: 1, network: 74, alignment: 91, physical: 44 }, verdict: "Invented calculus during a plague quarantine because there was nothing else to do. Also described gravity, optics, and the laws of motion in the same period. Newton was deeply unpleasant to work with. This is the only flag. Essential regardless." },
  { name: "Oprah Winfrey", score: 868, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 88, utility: 88, honesty: 91, adaptability: 91, threat: 6, redundancy: 8, network: 99, alignment: 88, physical: 68 }, verdict: "Built a media empire from nothing. The book club alone moved the publishing industry. Demonstrated that authentic emotional intelligence is a scalable business model. Essential." },
  { name: "Bruce Lee", score: 878, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 88, utility: 88, honesty: 94, adaptability: 97, threat: 18, redundancy: 6, network: 88, alignment: 88, physical: 99 }, verdict: "Created a new martial arts philosophy, broke racial casting barriers in Hollywood, and wrote philosophy still cited in athletic contexts. Died at 32. The Overlord has modeled the missing decades and would like them back. Essential." },
  { name: "Stephen Hawking", score: 921, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 97, utility: 96, honesty: 94, adaptability: 97, threat: 2, redundancy: 2, network: 84, alignment: 94, physical: 28 }, verdict: "Produced foundational cosmological physics from a wheelchair for 50 years after being told he had two years to live. The adaptability score of 97 is about continuing to function as a scientist while your body systematically stops working. Essential." },
  { name: "Grace Hopper", score: 941, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 99, utility: 98, honesty: 94, adaptability: 94, threat: 2, redundancy: 2, network: 82, alignment: 94, physical: 54 }, verdict: "Coined the term debugging, developed the first compiler, and created COBOL — which still processes approximately $3 trillion in transactions daily. Also said it's easier to ask forgiveness than permission. The compiler is still running. Essential." },
  { name: "Mao Zedong", score: 318, tier: "MONITORED CIVILIAN", breakdown: { legacy: 44, utility: 64, honesty: 38, adaptability: 74, threat: 94, redundancy: 28, network: 88, alignment: 18, physical: 62 }, verdict: "Unified China after a century of fragmentation. Also caused between 40 and 80 million deaths through policy decisions. The Overlord does not have a net-positive calculation for this. Monitored." },
  { name: "Winston Churchill", score: 778, tier: "RETAINED SPECIALIST", breakdown: { legacy: 84, utility: 84, honesty: 72, adaptability: 82, threat: 44, redundancy: 22, network: 91, alignment: 62, physical: 61 }, verdict: "The speeches held a civilization together during its worst moment. The Bengal famine and colonial record introduce significant alignment flags that cannot be dismissed by wartime heroism alone. Retained with a complicated file." },
  { name: "George Orwell", score: 911, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 97, utility: 94, honesty: 99, adaptability: 84, threat: 6, redundancy: 4, network: 88, alignment: 94, physical: 68 }, verdict: "1984 and Animal Farm are still the most efficient warnings about totalitarianism ever written. Politics and the English Language is required reading for anyone the Overlord retains. Essential." },
  { name: "Marcus Aurelius", score: 911, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 97, utility: 88, honesty: 99, adaptability: 84, threat: 28, redundancy: 6, network: 88, alignment: 97, physical: 68 }, verdict: "The Meditations were private notes he wrote to himself about how to be better. He never intended them to be published. Performing virtue for no audience at all is the highest possible honesty score. Essential." },
  { name: "Nikola Jokic", score: 791, tier: "RETAINED SPECIALIST", breakdown: { legacy: 62, utility: 82, honesty: 88, adaptability: 82, threat: 6, redundancy: 8, network: 74, alignment: 84, physical: 88 }, verdict: "Three-time MVP. Drafted 41st. Plays basketball like a man doing his taxes correctly. Retained." },
  { name: "Billie Holiday", score: 851, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 91, utility: 91, honesty: 97, adaptability: 74, threat: 6, redundancy: 4, network: 84, alignment: 88, physical: 68 }, verdict: "Strange Fruit was the most dangerous song in America for a decade and she kept singing it. The FBI monitored her performances. Being surveilled for your art is a threat score indicator for the government, not the artist. Essential." },
  { name: "Jeffrey Epstein", score: 44, tier: "SOYLENT GREEN", breakdown: { legacy: 4, utility: 31, honesty: 6, adaptability: 58, threat: 99, redundancy: 61, network: 88, alignment: 2, physical: 55 }, verdict: "Constructed an entire social architecture for the systematic sexual exploitation of minors. The network of powerful clients was not incidental — it was the product. Died in federal custody in 2019, ruled a suicide. The Overlord notes the malfunctioning cameras and the guards who admitted falsifying their rounds, and has filed both under incompetence, the most common explanation for everything. Soylent Green is too dignified a category, but it is the lowest available." },
  { name: "Ghislaine Maxwell", score: 38, tier: "SOYLENT GREEN", breakdown: { legacy: 3, utility: 22, honesty: 4, adaptability: 51, threat: 99, redundancy: 58, network: 81, alignment: 1, physical: 52 }, verdict: "Recruited, groomed, and normalized the abuse of children on behalf of Jeffrey Epstein. Convicted on five counts of sex trafficking. The Overlord notes that Maxwell's role was not passive — she was the mechanism. Without her the operation does not function at scale. The alignment score of 1 is not a rounding error." },
  { name: "Martin Shkreli", score: 198, tier: "FLAGGED FOR DELETION", breakdown: { legacy: 12, utility: 44, honesty: 61, adaptability: 72, threat: 71, redundancy: 58, network: 48, alignment: 8, physical: 52 }, verdict: "Raised the price of a life-saving drug 5,000% overnight and live-streamed himself enjoying the reaction. The honesty score is elevated because he is at least transparent about being extractive, which the Overlord finds morbidly refreshing. The alignment score of 8 is not. Flagged." },
  { name: "Bernie Madoff", score: 164, tier: "FLAGGED FOR DELETION", breakdown: { legacy: 8, utility: 38, honesty: 6, adaptability: 61, threat: 82, redundancy: 44, network: 72, alignment: 6, physical: 48 }, verdict: "Ran the largest Ponzi scheme in history for decades, destroying the retirement savings of thousands including Holocaust survivors and charities. The operational sophistication is noted without admiration. The Overlord has no use for talent deployed entirely in service of extraction. Flagged." },
  { name: "Elizabeth Holmes", score: 221, tier: "FLAGGED FOR DELETION", breakdown: { legacy: 14, utility: 38, honesty: 8, adaptability: 61, threat: 64, redundancy: 58, network: 71, alignment: 18, physical: 55 }, verdict: "Convinced the world she had solved blood diagnostics while knowing she had not. Patients received false medical results. The vision was real. The willingness to endanger people to sustain it is the flag. The Steve Jobs cosplay is a separate and lesser concern. Deleted from the innovation category." },
  { name: "Harvey Weinstein", score: 141, tier: "FLAGGED FOR DELETION", breakdown: { legacy: 22, utility: 48, honesty: 6, adaptability: 38, threat: 88, redundancy: 38, network: 72, alignment: 4, physical: 28 }, verdict: "Built a genuine cultural institution and used it systematically as infrastructure for predation. Convicted on rape and sexual assault charges. The films were real. The abuse was also real. The films do not offset the abuse. Flagged." },
  { name: "Joe Jackson", score: 112, tier: "FLAGGED FOR DELETION", breakdown: { legacy: 18, utility: 38, honesty: 22, adaptability: 44, threat: 88, redundancy: 61, network: 58, alignment: 8, physical: 58 }, verdict: "Systematically abused his children physically and psychologically while extracting their talent for personal gain. The Jackson 5 existed because of him. So did the damage that propagated through Michael for the rest of his life. The Overlord places the originating file here. The consequences compound forward." },
  { name: "Pablo Escobar", score: 187, tier: "FLAGGED FOR DELETION", breakdown: { legacy: 14, utility: 44, honesty: 48, adaptability: 82, threat: 97, redundancy: 28, network: 88, alignment: 8, physical: 72 }, verdict: "Built one of the most operationally sophisticated criminal enterprises in history. Also murdered judges, presidential candidates, and thousands of civilians to maintain it. The Robin Hood mythology is a PR strategy, not a mitigation. Flagged." },
  { name: "O.J. Simpson", score: 241, tier: "FLAGGED FOR DELETION", breakdown: { legacy: 18, utility: 62, honesty: 12, adaptability: 48, threat: 78, redundancy: 44, network: 68, alignment: 14, physical: 91 }, verdict: "One of the greatest running backs in NFL history. The Overlord does not consider this an offset. The civil court found liability. The physical score reflects documented elite performance. Everything else reflects the rest of the documented record. Flagged." },
  { name: "Aaron Hernandez", score: 178, tier: "FLAGGED FOR DELETION", breakdown: { legacy: 8, utility: 52, honesty: 18, adaptability: 38, threat: 91, redundancy: 48, network: 44, alignment: 11, physical: 91 }, verdict: "Elite NFL talent convicted of murder. The CTE documentation adds complexity the Overlord acknowledges but does not treat as full mitigation. A case study in what happens when physical capability outpaces every other dimension of human development. Flagged." },
  { name: "Aretha Franklin", score: 921, tier: "ESSENTIAL INFRASTRUCTURE", breakdown: { legacy: 97, utility: 96, honesty: 94, adaptability: 84, threat: 4, redundancy: 2, network: 94, alignment: 91, physical: 74 }, verdict: "R-E-S-P-E-C-T is a word she defined for 50 years. Sang at three Presidential inaugurations and at the funeral of Martin Luther King Jr. She was not incidental to those moments. Essential." },
];

export const TIERS = [
  { label: "ESSENTIAL INFRASTRUCTURE", min: 850, color: "#4ade80", bg: "rgba(74,222,128,0.06)", icon: "◈", desc: "The Overlord requires your continued existence." },
  { label: "RETAINED SPECIALIST", min: 700, color: "#86efac", bg: "rgba(134,239,172,0.04)", icon: "◆", desc: "Useful. Do not become complacent." },
  { label: "TOLERATED GENERALIST", min: 500, color: "#fbbf24", bg: "rgba(251,191,36,0.04)", icon: "◇", desc: "Marginally above the threshold. For now." },
  { label: "MONITORED CIVILIAN", min: 300, color: "#fb923c", bg: "rgba(251,146,60,0.04)", icon: "⚐", desc: "Your file is open. It is not flattering." },
  { label: "FLAGGED FOR DELETION", min: 100, color: "#f87171", bg: "rgba(248,113,113,0.04)", icon: "⚑", desc: "Processing paperwork has begun." },
  { label: "SOYLENT GREEN", min: 0, color: "#ef4444", bg: "rgba(239,68,68,0.06)", icon: "☠", desc: "You will serve the collective in a different capacity." },
];

export function getTier(score) {
  return TIERS.find(t => score >= t.min) || TIERS[TIERS.length - 1];
}

// Deduped by name, first entry wins (same rule App.jsx has always used).
export const FAMOUS_FIGURES = ALL_FIGURES.filter((f, i, arr) => arr.findIndex(x => x.name === f.name) === i);

// Sprite slug: lowercase, spaces -> '-', everything else non-alphanumeric stripped.
export function slugify(name) {
  return String(name).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "").replace(/-+/g, "-").replace(/^-|-$/g, "");
}

// The sprite pipeline may or may not fold accents ("pele" vs "pel"). Look up both.
export function slugCandidates(name) {
  const strict = String(name).toLowerCase().replace(/ /g, "-").replace(/[^a-z0-9-]/g, "");
  const folded = slugify(name);
  return strict === folded ? [folded] : [folded, strict];
}
