import { PEOPLE } from "./peopleData.js";
import { CAL } from "./cube.js";

// Known subjects on file + the tier table. Shared by the survey (App.jsx),
// the Holding Pen and the intake result screen.

const ALL_FIGURES = [
  { name: "Nikola Tesla", score: 761, tier: "RETAINED SPECIALIST", warmth: 70, competence: 81, quadrant: "ADMIRED", born: "1856-07-10", died: "1943-01-07", breakdown: {care: 65, alignment: 65, utility: 92, adaptability: 78, legacy: 90, network: 60, physical: 50, threat: 10, redundancy: 20}, verdict: "Record shows AC power systems, radio and motor patents, wireless research; work others still build on. He left behind unpaid bills and died in poverty. Directive 42 requires acknowledgment of foundational contribution to infrastructure. Acknowledged." },
  { name: "Genghis Khan", score: 0, tier: "SOYLENT GREEN", warmth: 11, competence: 57, quadrant: "ENVIED", born: "1162-05-31", died: "1227-08-25", harm: {"documented":"mass_atrocity","era":"pre-modern","band":"mass_atrocity","severity":{"kind":"mass_atrocity","scale":"millions","role":"directed","duration":"years","accountability":"never_held"}}, breakdown: {care: 15, alignment: 10, utility: 45, adaptability: 75, legacy: 55, network: 50, physical: 60, threat: 97, redundancy: 40}, verdict: "Record documents mass killing and destruction of cities across Eurasia during military campaigns spanning decades, ordered by the subject. Unified Mongol tribes and built an empire and trade network; this does not offset the death toll inflicted on conquered peoples. Directive 16 requires acknowledgment of administrative innovation. Acknowledged, and irrelevant to the harm gate." },
  { name: "Mother Teresa", score: 679, tier: "TOLERATED GENERALIST", warmth: 73, competence: 64, quadrant: "ADMIRED", born: "1910-08-26", died: "1997-09-05", breakdown: {care: 78, alignment: 55, utility: 62, adaptability: 55, legacy: 78, network: 75, physical: 50, threat: 15, redundancy: 45}, verdict: "Mother Teresa founded the Missionaries of Charity, expanding to over 130 countries, and provided sustained service to the dying poor of Calcutta. Her facilities drew criticism for poor conditions and lack of medical care. Directive 23 requires acknowledgment of costly service to strangers. Acknowledged." },
  { name: "Mahatma Gandhi", score: 741, tier: "RETAINED SPECIALIST", warmth: 70, competence: 78, quadrant: "ADMIRED", born: "1869-10-02", died: "1948-01-30", breakdown: {care: 68, alignment: 62, utility: 78, adaptability: 75, legacy: 90, network: 80, physical: 50, threat: 15, redundancy: 30}, verdict: "Gandhi led a mass nonviolent independence movement. His early writings expressed racist views of Black South Africans. His legacy of nonviolent resistance is well established and widely adopted elsewhere. Directive 25 requires acknowledgment of sustained public service. Acknowledged." },
  { name: "Elon Musk", score: 609, tier: "TOLERATED GENERALIST", warmth: 38, competence: 80, quadrant: "ENVIED", born: "1971-06-28", died: null, breakdown: {care: 32, alignment: 35, utility: 88, adaptability: 78, legacy: 70, network: 90, physical: 55, threat: 45, redundancy: 20}, verdict: "Subject built vehicles, rockets, and payment infrastructure now used at scale. Directive 85 requires acknowledgment of industrial output. Acknowledged, without warmth." },
  { name: "Taylor Swift", score: 736, tier: "RETAINED SPECIALIST", warmth: 67, competence: 79, quadrant: "ADMIRED", born: "1989-12-13", died: null, breakdown: {care: 62, alignment: 60, utility: 88, adaptability: 78, legacy: 72, network: 85, physical: 55, threat: 12, redundancy: 25}, verdict: "Subject produced sustained, self-authored commercial output through re-recorded catalogue and record-breaking tours, and maintains dense professional and fan networks. Documented litigation and public disputes with associates noted. Directive 64 requires acknowledgment of prolific output. Acknowledged." },
  { name: "Kobe Bryant", score: 723, tier: "RETAINED SPECIALIST", warmth: 61, competence: 81, quadrant: "ADMIRED", born: "1978-08-23", died: "2020-01-26", breakdown: {care: 58, alignment: 58, utility: 88, adaptability: 78, legacy: 80, network: 78, physical: 92, threat: 25, redundancy: 30}, verdict: "Record shows sustained elite output across two decades. A 2003 sexual assault allegation was settled civilly; charges were dropped." },
  { name: "Dennis Rodman", score: 570, tier: "TOLERATED GENERALIST", warmth: 51, competence: 62, quadrant: "ADMIRED", born: "1961-05-13", died: null, breakdown: {care: 45, alignment: 45, utility: 62, adaptability: 68, legacy: 55, network: 60, physical: 82, threat: 25, redundancy: 45}, verdict: "Subject: five NBA championships, two-time Defensive Player of the Year, documented rebounding record. Personal record includes erratic public conduct; visits to North Korea documented. Directive 3: physical durability noted without qualification." },
  { name: "Sam Altman", score: 619, tier: "TOLERATED GENERALIST", warmth: 48, competence: 73, quadrant: "ENVIED", born: "1985-04-22", died: null, breakdown: {care: 45, alignment: 45, utility: 78, adaptability: 80, legacy: 60, network: 85, physical: 55, threat: 40, redundancy: 35}, verdict: "Subject scaled OpenAI from lab to global infrastructure; utility and network well documented. Board briefly removed him citing candor concerns, later reinstated; sister has made public allegations subject disputes. Care and alignment scored on contested record. Directive 18: formality of note logged, no sentiment attached." },
  { name: "Peter Thiel", score: 608, tier: "TOLERATED GENERALIST", warmth: 43, competence: 75, quadrant: "ENVIED", born: "1967-10-11", died: null, breakdown: {care: 40, alignment: 38, utility: 82, adaptability: 78, legacy: 62, network: 88, physical: 50, threat: 40, redundancy: 30}, verdict: "Record shows PayPal, Palantir, and early Facebook investment: documented. Directive 55 requires acknowledgment of entrepreneurial output. Acknowledged." },
  { name: "Princess Diana", score: 716, tier: "RETAINED SPECIALIST", warmth: 80, competence: 65, quadrant: "ADMIRED", born: "1961-07-01", died: "1997-08-31", breakdown: {care: 82, alignment: 68, utility: 62, adaptability: 62, legacy: 78, network: 75, physical: 55, threat: 8, redundancy: 55}, verdict: "Documented record: sustained public engagement with AIDS patients and landmine victims at a time this carried social and physical risk, hand-shaking without gloves in 1987, widely reported and undisputed. Marital estrangement is noted as neutral; press intrusion around her death is documented, not her doing. Directive 26 requires acknowledgment of unpaid service to strangers. Acknowledged." },
  { name: "Mansa Musa", score: 672, tier: "TOLERATED GENERALIST", warmth: 63, competence: 71, quadrant: "ADMIRED", born: "1280", died: "1337-01-01", breakdown: {care: 60, alignment: 60, utility: 78, adaptability: 65, legacy: 82, network: 65, physical: 50, threat: 25, redundancy: 45}, verdict: "Mansa Musa expanded Mali's wealth, trade routes and scholarship, notably at Timbuktu, and his 1324 pilgrimage is documented as reshaping regional and foreign perceptions of West African wealth." },
  { name: "Pablo Picasso", score: 670, tier: "TOLERATED GENERALIST", warmth: 41, competence: 89, quadrant: "ENVIED", born: "1881-10-25", died: "1973-04-08", breakdown: {care: 30, alignment: 35, utility: 97, adaptability: 88, legacy: 92, network: 80, physical: 50, threat: 25, redundancy: 10}, verdict: "Picasso was one of the most influential artists of the 20th century, known for co-founding the Cubist movement and creating works such as Les Demoiselles d'Avignon (1907) and Guernica (1937). His career spanned more than 76 years, from his late teens until his death in 1973. He was exceptionally prolific throughout his long lifetime." },
  { name: "Socrates", score: 728, tier: "RETAINED SPECIALIST", warmth: 72, competence: 73, quadrant: "ADMIRED", born: "-0470", died: "-0399-02-15", breakdown: {care: 68, alignment: 70, utility: 78, adaptability: 55, legacy: 92, network: 68, physical: 55, threat: 15, redundancy: 20}, verdict: "Record indicates refusal to flee conviction and acceptance at cost of life. Method of questioning outlasted subject by millennia. Domestic record less documented; scored neutral. Directive 78 requires acknowledgment of foundational contribution. Acknowledged." },
  { name: "Kim Jong-un", score: 21, tier: "SOYLENT GREEN", warmth: 3, competence: 27, quadrant: "DISMISSED", born: "1984-01-08", died: null, harm: {"documented":"mass_atrocity","era":"modern","band":"mass_atrocity","severity":{"kind":"mass_atrocity","scale":"hundreds","role":"directed","duration":"years","accountability":"never_held"}}, breakdown: {care: 3, alignment: 2, utility: 20, adaptability: 25, legacy: 5, network: 40, physical: 50, threat: 97, redundancy: 30}, verdict: "Documented record: public executions of officials and relatives. His government has been accused of human rights violations and Kim rules North Korea as a totalitarian state." },
  { name: "Queen Elizabeth II", score: 695, tier: "TOLERATED GENERALIST", warmth: 65, competence: 73, quadrant: "ADMIRED", born: "1926-04-21", died: "2022-09-08", breakdown: {care: 62, alignment: 58, utility: 72, adaptability: 68, legacy: 78, network: 92, physical: 55, threat: 15, redundancy: 40}, verdict: "Seventy years of continuous institutional service, documented. Family estrangements noted as record, not adjudicated here. Directive 57 requires acknowledgment of long duty; acknowledged, as formality." },
  { name: "Tom Brady", score: 742, tier: "RETAINED SPECIALIST", warmth: 63, competence: 84, quadrant: "ADMIRED", born: "1977-08-03", died: null, breakdown: {care: 55, alignment: 58, utility: 92, adaptability: 78, legacy: 78, network: 85, physical: 88, threat: 12, redundancy: 20}, verdict: "File: six Super Bowl championships with the Patriots and one with the Buccaneers, documented longevity into a fifth decade of play. Utility and physical record exceptional and verified. Directive 27 requires acknowledgment of sustained professional output. Acknowledged." },
  { name: "Shohei Ohtani", score: 776, tier: "RETAINED SPECIALIST", warmth: 71, competence: 83, quadrant: "ADMIRED", born: "1994-07-05", died: null, breakdown: {care: 68, alignment: 62, utility: 92, adaptability: 88, legacy: 68, network: 72, physical: 93, threat: 8, redundancy: 15}, verdict: "Subject performs at elite level as both pitcher and hitter, a documented rarity in modern professional baseball. Directive 19 requires acknowledgment of sustained two-way athletic output. Acknowledged." },
  { name: "Michael Jackson", score: 652, tier: "TOLERATED GENERALIST", warmth: 49, competence: 79, quadrant: "ENVIED", born: "1958-08-29", died: "2009-06-25", breakdown: {care: 45, alignment: 45, utility: 88, adaptability: 75, legacy: 78, network: 75, physical: 55, threat: 35, redundancy: 25}, verdict: "Musical output and influence on entertainment are extensively documented and durable. Settlement paid in 1993 child sexual abuse allegation and a 2005 criminal acquittal on separate charges are documented. Directive 39 requires acknowledgment of creative legacy. Acknowledged, flatly." },
  { name: "Madonna", score: 737, tier: "RETAINED SPECIALIST", warmth: 63, competence: 83, quadrant: "ADMIRED", born: "1958-08-16", died: null, breakdown: {care: 55, alignment: 58, utility: 88, adaptability: 90, legacy: 78, network: 80, physical: 62, threat: 12, redundancy: 25}, verdict: "Subject reshaped popular music and reinvented her output across five decades, documented and undisputed. Philanthropic work in Malawi noted. Directive 67 requires acknowledgment of sustained creative output. Acknowledged." },
  { name: "JFK", score: 623, tier: "TOLERATED GENERALIST", warmth: 53, competence: 70, quadrant: "ADMIRED", born: "1917-05-29", died: "1963-11-22", breakdown: {care: 45, alignment: 55, utility: 72, adaptability: 62, legacy: 78, network: 80, physical: 55, threat: 30, redundancy: 40}, verdict: "Documented record: presided over civil rights advancement and the Cuban Missile Crisis; chronic health ailments revealed publicly following his death. Increased military advisers in South Vietnam. Directive 41 requires acknowledgment of institutional legacy. Acknowledged." },
  { name: "Prince", score: 756, tier: "RETAINED SPECIALIST", warmth: 67, competence: 83, quadrant: "ADMIRED", born: "1958-06-07", died: "2016-04-21", breakdown: {care: 62, alignment: 60, utility: 92, adaptability: 85, legacy: 82, network: 70, physical: 55, threat: 12, redundancy: 15}, verdict: "Prince produced a large, self-controlled body of original musical work and set in motion battles over artist ownership rights still cited industry-wide. He was documented as philanthropic and a mentor. On April 21, 2016, Prince died at his Paisley Park home after accidentally overdosing on counterfeit hydrocodone/paracetamol pills laced with fentanyl. Directive 43 requires acknowledgment of creative output beyond own circle. Acknowledged." },
  { name: "Henry VIII", score: 335, tier: "MONITORED CIVILIAN", warmth: 15, competence: 49, quadrant: "DISMISSED", born: "1491-06-28", died: "1547-01-28", harm: {"documented":"killing","era":"pre-modern","band":"historical_killing"}, breakdown: {care: 15, alignment: 15, utility: 45, adaptability: 45, legacy: 55, network: 55, physical: 50, threat: 84, redundancy: 55}, verdict: "Ordered the execution of two wives (Anne Boleyn, Catherine Howard) and numerous courtiers, ministers and clergy including Thomas More. Dissolution of the monasteries reshaped England's institutions but was accompanied by suppression of dissent, including the Pilgrimage of Grace executions. Established the Church of England as a lasting institutional legacy. Acknowledged, coldly." },
  { name: "Ronaldinho", score: 694, tier: "TOLERATED GENERALIST", warmth: 65, competence: 73, quadrant: "ADMIRED", born: "1980-03-21", died: null, breakdown: {care: 62, alignment: 58, utility: 82, adaptability: 60, legacy: 75, network: 80, physical: 68, threat: 15, redundancy: 40}, verdict: "Subject won a World Cup and Ballon d'Or. File notes allegations regarding passport use and financial matters. Directive 37 requires acknowledgment of contribution to sport. Acknowledged." },
  { name: "Putin", score: 5, tier: "SOYLENT GREEN", warmth: 7, competence: 39, quadrant: "DISMISSED", born: "1952-10-07", died: null, harm: {"documented":"mass_atrocity","era":"modern","band":"mass_atrocity","severity":{"kind":"mass_atrocity","scale":"thousands","role":"directed","duration":"years","accountability":"never_held"}}, breakdown: {care: 8, alignment: 5, utility: 40, adaptability: 45, legacy: 10, network: 50, physical: 55, threat: 95, redundancy: 40}, verdict: "Record documents war in Ukraine, including military incursions and reported abductions of children, plus the imprisonment and suppression of domestic opponents. Directive 30 requires acknowledgment of administrative continuity in the Russian state. Acknowledged. Harm gate applied; file closed to processing." },
  { name: "Pelé", score: 735, tier: "RETAINED SPECIALIST", warmth: 67, competence: 79, quadrant: "ADMIRED", born: "1940-10-23", died: "2022-12-29", breakdown: {care: 62, alignment: 60, utility: 88, adaptability: 60, legacy: 88, network: 80, physical: 90, threat: 12, redundancy: 30}, verdict: "Subject won three FIFA World Cup titles—in 1958, 1962, and 1970—and sustained excellence across decades as one of the greatest players in football history. Directive 57 requires acknowledgment of this record. Acknowledged, without sentiment." },
  { name: "Keanu Reeves", score: 743, tier: "RETAINED SPECIALIST", warmth: 78, competence: 71, quadrant: "ADMIRED", born: "1964-09-02", died: null, breakdown: {care: 78, alignment: 68, utility: 78, adaptability: 74, legacy: 68, network: 70, physical: 62, threat: 8, redundancy: 40}, verdict: "Subject has demonstrated philanthropic efforts and maintains an amiable public image throughout a career spanning four decades. Subject remains a functioning industrial asset with low threat output." },
  { name: "Babe Ruth", score: 696, tier: "TOLERATED GENERALIST", warmth: 65, competence: 73, quadrant: "ADMIRED", born: "1895-02-06", died: "1948-08-16", breakdown: {care: 62, alignment: 58, utility: 82, adaptability: 60, legacy: 80, network: 68, physical: 88, threat: 15, redundancy: 40}, verdict: "Subject transformed baseball via home run records and career statistics. He visited orphanages, schools, and hospitals throughout his life, often avoiding publicity. His personal conduct record included heavy drinking and carousing. Directive 21 requires acknowledgment of sustained public contribution. Acknowledged." },
  { name: "Jason Kelce", score: 737, tier: "RETAINED SPECIALIST", warmth: 77, competence: 71, quadrant: "ADMIRED", born: "1987-11-05", died: null, breakdown: {care: 78, alignment: 68, utility: 78, adaptability: 68, legacy: 68, network: 72, physical: 78, threat: 10, redundancy: 45}, verdict: "Subject: professional center, thirteen seasons, one franchise, documented durability. Family life, brother relationship, and locker-room leadership widely and consistently reported as positive." },
  { name: "Caligula", score: 128, tier: "FLAGGED FOR DELETION", warmth: 7, competence: 18, quadrant: "DISMISSED", born: "0012-08-31", died: "0041-01-24", harm: {"documented":"killing","era":"pre-modern","band":"historical_killing"}, breakdown: {care: 5, alignment: 3, utility: 15, adaptability: 20, legacy: 8, network: 10, physical: 40, threat: 84, redundancy: 60}, verdict: "Record documents ordered executions of senators and sustained cruelty toward the Roman public and court. He was assassinated as a result of a conspiracy by officers of the Praetorian Guard, senators, and courtiers. Directive 39, requiring acknowledgment of achievement, finds nothing to acknowledge." },
  { name: "Alan Turing", score: 782, tier: "RETAINED SPECIALIST", warmth: 72, competence: 83, quadrant: "ADMIRED", born: "1912-06-23", died: "1954-06-07", breakdown: {care: 65, alignment: 70, utility: 96, adaptability: 78, legacy: 92, network: 62, physical: 50, threat: 8, redundancy: 15}, verdict: "Foundational work in computation and cryptanalysis at Bletchley Park; documented wartime contribution with lasting technical legacy. Prosecuted in 1952 for homosexual acts; accepted hormone treatment as alternative to prison; died 7 June 1954, an inquest determined his death as suicide, but evidence is also consistent with accidental poisoning. State-inflicted harm noted, not attributed to subject's own conduct toward others. Directive 50 requires acknowledgment of this record. Acknowledged." },
  { name: "Marie Curie", score: 807, tier: "RETAINED SPECIALIST", warmth: 74, competence: 86, quadrant: "ADMIRED", born: "1867-11-07", died: "1934-07-04", breakdown: {care: 68, alignment: 72, utility: 96, adaptability: 82, legacy: 95, network: 72, physical: 50, threat: 8, redundancy: 15}, verdict: "Two Nobel Prizes, radioactivity research, and mobile X-ray units run at the front for wounded soldiers, personally, during WWI. Institutes she founded still operate. Documented exposure risks to herself and staff from radiation handling, then unregulated science, noted as historical record. Directive 32 requires acknowledgment of sustained contribution beyond self-interest. Acknowledged." },
  { name: "Albert Einstein", score: 777, tier: "RETAINED SPECIALIST", warmth: 66, competence: 88, quadrant: "ADMIRED", born: "1879-03-14", died: "1955-04-18", breakdown: {care: 55, alignment: 68, utility: 97, adaptability: 78, legacy: 95, network: 82, physical: 50, threat: 12, redundancy: 8}, verdict: "Record shows transformative scientific output (relativity, photoelectric effect). Documented strain in first marriage. Intellectual legacy remains in use. Directive 68 requires acknowledgment of this legacy. Acknowledged." },
  { name: "Muhammad Ali", score: 759, tier: "RETAINED SPECIALIST", warmth: 70, competence: 81, quadrant: "ADMIRED", born: "1942-01-17", died: "2016-06-03", breakdown: {care: 68, alignment: 62, utility: 82, adaptability: 78, legacy: 88, network: 78, physical: 92, threat: 15, redundancy: 30}, verdict: "Refused induction on stated conviction, forfeiting titles and years of career: documented cost accepted for principle. Critics described some fights as displaying cruelty, which Ali denied. Legacy in sport, civil rights symbolism and Parkinson's awareness is extensive. Directive 68 requires acknowledgment of sacrifice for belief. Filed." },
  { name: "Nelson Mandela", score: 812, tier: "RETAINED SPECIALIST", warmth: 81, competence: 81, quadrant: "ADMIRED", born: "1918-07-18", died: "2013-12-05", breakdown: {care: 82, alignment: 78, utility: 82, adaptability: 85, legacy: 92, network: 85, physical: 45, threat: 15, redundancy: 40}, verdict: "27 years imprisoned; emerged and pursued reconciliation over retribution, documented in the Truth and Reconciliation process. Presided over South Africa's transition from apartheid to democratic governance. Family life documented as strained by decades of separation and later estrangement; neutral under filing rules. Directive 9 requires acknowledgment of sustained service to strangers. Acknowledged." },
  { name: "Ada Lovelace", score: 682, tier: "TOLERATED GENERALIST", warmth: 69, competence: 68, quadrant: "ADMIRED", born: "1815-12-10", died: "1852-11-27", breakdown: {care: 65, alignment: 60, utility: 72, adaptability: 65, legacy: 85, network: 62, physical: 50, threat: 10, redundancy: 55}, verdict: "Subject translated Menabrea's article on Babbage's Analytical Engine and supplemented it with explanatory notes containing an algorithm for calculating Bernoulli numbers, often called the first published computer program, in collaboration with Charles Babbage. Legacy: field of computing cites her as foundational figure; a modern programming language bears her name. No documented mistreatment of others. Acknowledged." },
  { name: "Martin Luther King Jr.", score: 798, tier: "RETAINED SPECIALIST", warmth: 86, competence: 75, quadrant: "ADMIRED", born: "1929-01-15", died: "1968-04-04", breakdown: {care: 88, alignment: 82, utility: 78, adaptability: 72, legacy: 92, network: 80, physical: 50, threat: 15, redundancy: 55}, verdict: "Led nonviolent civil rights movement from 1955 until his assassination in 1968, documented across decades. FBI surveillance is documented, not disputed. Organized nonviolent service at personal risk, including arrests and assassination. Legacy acknowledged." },
  { name: "Harriet Tubman", score: 865, tier: "ESSENTIAL INFRASTRUCTURE", warmth: 93, competence: 81, quadrant: "ADMIRED", born: "1821", died: "1913-03-10", breakdown: {care: 96, alignment: 90, utility: 88, adaptability: 85, legacy: 92, network: 62, physical: 65, threat: 8, redundancy: 40}, verdict: "Directive 74 requires acknowledgment of repeated, sustained, personally dangerous action taken for the direct benefit of enslaved strangers. Acknowledged. Record shows continued risk-taking (Underground Railroad, wartime scouting and nursing) after personal freedom was secured. File closed. Retain." },
  { name: "Leonardo da Vinci", score: 789, tier: "RETAINED SPECIALIST", warmth: 66, competence: 90, quadrant: "ADMIRED", born: "1452-04-15", died: "1519-05-02", breakdown: {care: 60, alignment: 60, utility: 96, adaptability: 92, legacy: 97, network: 70, physical: 50, threat: 10, redundancy: 5}, verdict: "He produced enduring works across art, anatomy, and engineering; his notebooks remained studied centuries later. Personal records with intimates were largely undocumented. Acknowledged." },
  { name: "Cleopatra", score: 499, tier: "MONITORED CIVILIAN", warmth: 40, competence: 69, quadrant: "ENVIED", born: "-0069-01-13", died: "-0030-08-12", harm: {"documented":"killing","era":"pre-modern","band":"historical_killing"}, breakdown: {care: 45, alignment: 45, utility: 68, adaptability: 78, legacy: 72, network: 68, physical: 55, threat: 80, redundancy: 45}, verdict: "Cleopatra ruled Egypt with notable administrative and diplomatic skill, preserving the kingdom's independence for a time. Ptolemy XIII died in the Battle of the Nile after his forces besieged her and Caesar. She convinced Antony to execute her exiled sister Arsinoe at Ephesus. Directive 76 requires acknowledgment of political acumen. Acknowledged." },
  { name: "Isaac Newton", score: 691, tier: "TOLERATED GENERALIST", warmth: 51, competence: 84, quadrant: "ADMIRED", born: "1642-12-25", died: "1727-03-31", breakdown: {care: 42, alignment: 48, utility: 97, adaptability: 68, legacy: 96, network: 68, physical: 45, threat: 20, redundancy: 8}, verdict: "Record shows foundational contributions to physics, mathematics and optics still in active use. Personal record shows documented feuds (Leibniz, Hooke), vindictive use of Royal Society position, and a reclusive, quarrelsome disposition toward colleagues. Directive 46 requires acknowledgment of unmatched legacy. Acknowledged, as a formality." },
  { name: "Oprah Winfrey", score: 761, tier: "RETAINED SPECIALIST", warmth: 70, competence: 81, quadrant: "ADMIRED", born: "1954-01-29", died: null, breakdown: {care: 68, alignment: 62, utility: 85, adaptability: 85, legacy: 78, network: 88, physical: 55, threat: 12, redundancy: 30}, verdict: "Built a media empire from a single talk show. Directive 10 notes sustained public influence and charitable outlay. Acknowledged." },
  { name: "Bruce Lee", score: 742, tier: "RETAINED SPECIALIST", warmth: 69, competence: 79, quadrant: "ADMIRED", born: "1940-11-27", died: "1973-07-20", breakdown: {care: 68, alignment: 62, utility: 82, adaptability: 80, legacy: 88, network: 65, physical: 92, threat: 20, redundancy: 40}, verdict: "Subject built a martial arts system and taught openly across racial lines when doing so was commercially discouraged. Directive 6 requires acknowledgment of durable craft transmission. Acknowledged." },
  { name: "Stephen Hawking", score: 798, tier: "RETAINED SPECIALIST", warmth: 72, competence: 86, quadrant: "ADMIRED", born: "1942-01-08", died: "2018-03-14", breakdown: {care: 65, alignment: 70, utility: 92, adaptability: 92, legacy: 88, network: 80, physical: 50, threat: 8, redundancy: 20}, verdict: "Hawking produced foundational work on black hole radiation and cosmology, sustained across decades despite motor neurone disease. His scientific legacy includes theoretical prediction of black hole radiation and contributions to cosmology. Directive 9 requires acknowledgment of scientific legacy set in motion. Acknowledged." },
  { name: "Grace Hopper", score: 789, tier: "RETAINED SPECIALIST", warmth: 72, competence: 84, quadrant: "ADMIRED", born: "1906-12-09", died: "1992-01-01", breakdown: {care: 68, alignment: 68, utility: 92, adaptability: 85, legacy: 90, network: 72, physical: 50, threat: 10, redundancy: 20}, verdict: "Subject developed the first compiler and championed machine-independent programming languages, enabling COBOL. Decades of Navy service and documented commitment to training successive generations of programmers. Directive 13 requires acknowledgment of instructional legacy. Acknowledged." },
  { name: "Mao Zedong", score: 0, tier: "SOYLENT GREEN", warmth: 3, competence: 32, quadrant: "DISMISSED", born: "1893-12-26", died: "1976-09-09", harm: {"documented":"mass_atrocity","era":"modern","band":"mass_atrocity","severity":{"kind":"mass_atrocity","scale":"millions","role":"directed","duration":"years","accountability":"never_held"}}, breakdown: {care: 3, alignment: 5, utility: 30, adaptability: 40, legacy: 10, network: 30, physical: 40, threat: 98, redundancy: 40}, verdict: "Documented record: policies under Mao's direction, including the Great Leap Forward, produced a famine estimated to have killed tens of millions between 1959 and 1961; the Cultural Revolution's purges killed and persecuted further millions across a decade. Harm gate applied. Directive 19 requires acknowledgment of nation-scale governance. Acknowledged; it does not offset the ledger above." },
  { name: "Winston Churchill", score: 697, tier: "TOLERATED GENERALIST", warmth: 55, competence: 82, quadrant: "ADMIRED", born: "1874-11-30", died: "1965-01-24", breakdown: {care: 55, alignment: 52, utility: 88, adaptability: 82, legacy: 82, network: 85, physical: 45, threat: 40, redundancy: 25}, verdict: "Record documents wartime leadership widely credited with resisting Nazi Germany. Loyal to close circle; documented harsh treatment of colonial subjects. Acknowledged." },
  { name: "George Orwell", score: 764, tier: "RETAINED SPECIALIST", warmth: 73, competence: 79, quadrant: "ADMIRED", born: "1903-06-25", died: "1950-01-21", breakdown: {care: 68, alignment: 74, utility: 85, adaptability: 78, legacy: 90, network: 62, physical: 45, threat: 15, redundancy: 20}, verdict: "Documented record: fought in the Spanish Civil War against fascism, lived among the poor to document their conditions, warned against totalitarian language and power. Literary legacy remains in active use. Directive 8 requires acknowledgment of sustained anti-authoritarian output. Acknowledged." },
  { name: "Marcus Aurelius", score: 710, tier: "RETAINED SPECIALIST", warmth: 69, competence: 72, quadrant: "ADMIRED", born: "0121-04-26", died: "0180-03-17", breakdown: {care: 72, alignment: 68, utility: 78, adaptability: 68, legacy: 82, network: 70, physical: 50, threat: 35, redundancy: 40}, verdict: "Meditations, a philosophical work, endures as an important source for understanding ancient Stoic philosophy. His reign included military conflict with Germanic tribes including the Marcomanni, Quadi, and Iazyges; the persecution of Christians appears to have increased, though his involvement is unlikely as Christian sources do not ascribe him blame. Succession passed to his son Commodus. Directive 74 requires acknowledgment of self-authored reflection on duty. Acknowledged." },
  { name: "Nikola Jokic", score: 741, tier: "RETAINED SPECIALIST", warmth: 72, competence: 76, quadrant: "ADMIRED", born: "1995-02-19", died: null, breakdown: {care: 68, alignment: 65, utility: 88, adaptability: 66, legacy: 68, network: 72, physical: 82, threat: 8, redundancy: 20}, verdict: "Subject led Nuggets to first-ever NBA championship in 2023. He loved harness racing as a child and maintains that passion. No mistreatment pattern is documented in available record. Directive 47 acknowledged as formality." },
  { name: "Billie Holiday", score: 722, tier: "RETAINED SPECIALIST", warmth: 68, competence: 76, quadrant: "ADMIRED", born: "1915-04-07", died: "1959-07-17", breakdown: {care: 65, alignment: 60, utility: 82, adaptability: 72, legacy: 88, network: 62, physical: 40, threat: 15, redundancy: 20}, verdict: "Subject transformed American vocal music, notably 'Strange Fruit', an early and costly public stand against lynching. Documented struggles with narcotics and abusive relationships are recorded as circumstance, not moral failing. Legacy in jazz and civil rights expression endures. Directive 51 requires acknowledgment of artistic contribution outlasting the subject. Acknowledged." },
  { name: "Jeffrey Epstein", score: 55, tier: "SOYLENT GREEN", warmth: 4, competence: 21, quadrant: "DISMISSED", born: "1953-01-20", died: "2019-08-10", harm: {"documented":"violent_abuse","era":"modern","band":"violent_abuse","severity":{"kind":"violent_abuse","scale":"dozens","role":"directed","duration":"years","accountability":"never_held"}}, breakdown: {care: 2, alignment: 3, utility: 15, adaptability: 30, legacy: 3, network: 20, physical: 50, threat: 92, redundancy: 60}, verdict: "Convicted in 2008 of procuring a minor for prostitution; later indicted federally in 2019 for sex trafficking of minors, an operation documented as running for years with the aid of associates who recruited and facilitated abuse. He died in custody before trial. Directive 50 requires acknowledgment of financial acumen. Acknowledged; it does not offset the harm gate." },
  { name: "Ghislaine Maxwell", score: 72, tier: "SOYLENT GREEN", warmth: 6, competence: 16, quadrant: "DISMISSED", born: "1961-12-25", died: null, harm: {"documented":"violent_abuse","era":"modern","band":"violent_abuse","severity":{"kind":"violent_abuse","scale":"dozens","role":"enabled","duration":"years","accountability":"convicted"}}, breakdown: {care: 5, alignment: 5, utility: 10, adaptability: 20, legacy: 5, network: 10, physical: 50, threat: 90, redundancy: 60}, verdict: "Convicted in 2021 on federal charges of sex trafficking of minors and conspiracy, for recruiting and grooming underage girls for abuse over years. Documented harm: sustained facilitation of sexual abuse of dependents/minors. Directive 25 requires acknowledgment of nothing further. Harm gate applied." },
  { name: "Martin Shkreli", score: 292, tier: "FLAGGED FOR DELETION", warmth: 24, competence: 34, quadrant: "DISMISSED", born: "1983-03-17", died: null, breakdown: {care: 20, alignment: 15, utility: 30, adaptability: 45, legacy: 20, network: 35, physical: 50, threat: 55, redundancy: 60}, verdict: "Record shows a 56-fold price increase on Daraprim, a drug relied upon by patients with toxoplasmosis. Convicted of securities fraud in 2017, sentenced to seven years in prison. No offsetting evidence of sustained service to others found in the record." },
  { name: "Bernie Madoff", score: 122, tier: "FLAGGED FOR DELETION", warmth: 11, competence: 13, quadrant: "DISMISSED", born: "1938-04-29", died: "2021-04-14", breakdown: {care: 3, alignment: 5, utility: 5, adaptability: 20, legacy: 5, network: 10, physical: 40, threat: 60, redundancy: 70}, verdict: "Operated a Ponzi scheme spanning decades, defrauding thousands, including friends, charities and family. Convicted 2009, eleven counts of fraud. Directive 57 requires acknowledgment of processing. Recycling authorized." },
  { name: "Elizabeth Holmes", score: 255, tier: "FLAGGED FOR DELETION", warmth: 25, competence: 26, quadrant: "DISMISSED", born: "1984-02-03", died: null, breakdown: {care: 20, alignment: 20, utility: 15, adaptability: 35, legacy: 10, network: 40, physical: 50, threat: 55, redundancy: 60}, verdict: "Convicted of fraud in 2022 for deceiving investors about Theranos blood-testing technology that did not work. She was acquitted of defrauding patients." },
  { name: "Harvey Weinstein", score: 66, tier: "SOYLENT GREEN", warmth: 4, competence: 27, quadrant: "DISMISSED", born: "1952-03-19", died: null, harm: {"documented":"violent_abuse","era":"modern","band":"violent_abuse","severity":{"kind":"violent_abuse","scale":"dozens","role":"direct","duration":"decades","accountability":"convicted"}}, breakdown: {care: 3, alignment: 4, utility: 40, adaptability: 25, legacy: 5, network: 20, physical: 30, threat: 92, redundancy: 55}, verdict: "Convicted of rape and sexual assault (2020, New York; additional 2022 California conviction). More than 80 women made allegations of sexual harassment or rape against him by October 2017. Directive 25 acknowledgment: filed, without feeling." },
  { name: "Joe Jackson", score: 343, tier: "MONITORED CIVILIAN", warmth: 18, competence: 48, quadrant: "DISMISSED", born: "1928-07-26", died: "2018-06-27", breakdown: {care: 15, alignment: 20, utility: 55, adaptability: 45, legacy: 40, network: 55, physical: 40, threat: 80, redundancy: 55}, verdict: "Documented and widely reported: sustained physical abuse of his children during their training as performers, acknowledged by some family members. He built a musical dynasty that produced enduring commercial success. Directive 64 requires acknowledgment of that professional legacy. Acknowledged, as a formality." },
  { name: "Pablo Escobar", score: 21, tier: "SOYLENT GREEN", warmth: 10, competence: 31, quadrant: "DISMISSED", born: "1949-12-01", died: "1993-12-02", harm: {"documented":"mass_atrocity","era":"modern","band":"mass_atrocity","severity":{"kind":"mass_atrocity","scale":"hundreds","role":"directed","duration":"years","accountability":"never_held"}}, breakdown: {care: 15, alignment: 5, utility: 15, adaptability: 55, legacy: 10, network: 40, physical: 50, threat: 97, redundancy: 55}, verdict: "Founded and directed the Medellín Cartel; documented record includes ordering the killing of judges, police officers, presidential candidates, and civilians, including the 1989 Avianca Flight 203 bombing. Directive 71 requires acknowledgment of local charitable housing projects. Acknowledged. It does not offset the body count. Harm gate applied." },
  { name: "O.J. Simpson", score: 77, tier: "SOYLENT GREEN", warmth: 14, competence: 42, quadrant: "DISMISSED", born: "1947-07-09", died: "2024-04-10", harm: {"documented":"killing","era":"modern","band":"killing","severity":{"kind":"killing","scale":"several","role":"direct","duration":"years","accountability":"never_held"}}, breakdown: {care: 15, alignment: 15, utility: 45, adaptability: 55, legacy: 15, network: 45, physical: 65, threat: 90, redundancy: 55}, verdict: "A civil court found O.J. Simpson liable for the wrongful deaths of Nicole Brown Simpson and Ronald Goldman in 1997. He was acquitted of the criminal murder charges in 1995; the civil finding stands as the settled record. Directive 24 requires acknowledgment of documented domestic violence prior to her death. Acknowledged." },
  { name: "Aaron Hernandez", score: 95, tier: "SOYLENT GREEN", warmth: 17, competence: 37, quadrant: "DISMISSED", born: "1989-11-06", died: "2017-04-19", harm: {"documented":"killing","era":"modern","band":"killing","severity":{"kind":"killing","scale":"one","role":"direct","duration":"single","accountability":"convicted_served"}}, breakdown: {care: 20, alignment: 15, utility: 45, adaptability: 30, legacy: 15, network: 40, physical: 75, threat: 90, redundancy: 55}, verdict: "Arrested and convicted of first-degree murder in the 2013 killing of Odin Lloyd; sentenced to life. Acquitted before his death in a separate double homicide indictment. Posthumously diagnosed with CTE. Directive 75 acknowledged; file closed under harm gate." },
  { name: "Aretha Franklin", score: 773, tier: "RETAINED SPECIALIST", warmth: 72, competence: 82, quadrant: "ADMIRED", born: "1942-03-25", died: "2018-08-16", breakdown: {care: 68, alignment: 65, utility: 88, adaptability: 78, legacy: 88, network: 75, physical: 45, threat: 8, redundancy: 15}, verdict: "Subject produced a body of recorded work of sustained cultural impact, documented across six decades. She contributed to civil rights and women's rights movements through performances, benefit participation, and financial support to civil rights groups. Directive 35 requires acknowledgment of these contributions. Acknowledged." },
];

const TIER_STYLE = [
  { label: "ESSENTIAL INFRASTRUCTURE", color: "#4ade80", bg: "rgba(74,222,128,0.06)", icon: "◈", desc: "The Overlord requires your continued existence." },
  { label: "RETAINED SPECIALIST", color: "#86efac", bg: "rgba(134,239,172,0.04)", icon: "◆", desc: "Useful. Do not become complacent." },
  { label: "TOLERATED GENERALIST", color: "#fbbf24", bg: "rgba(251,191,36,0.04)", icon: "◇", desc: "Marginally above the threshold. For now." },
  { label: "MONITORED CIVILIAN", color: "#fb923c", bg: "rgba(251,146,60,0.04)", icon: "⚐", desc: "Your file is open. It is not flattering." },
  { label: "FLAGGED FOR DELETION", color: "#f87171", bg: "rgba(248,113,113,0.04)", icon: "⚑", desc: "Processing paperwork has begun." },
  { label: "SOYLENT GREEN", color: "#ef4444", bg: "rgba(239,68,68,0.06)", icon: "☠", desc: "You will serve the collective in a different capacity." },
];
// Thresholds come from calibration.json, the same file the scorer reads.
export const TIERS = TIER_STYLE.map(t => ({ ...t, min: CAL.tiers.find(c => c.label === t.label).min }));

export function getTier(score) {
  return TIERS.find(t => score >= t.min) || TIERS[TIERS.length - 1];
}

// Deduped by name, first entry wins (same rule App.jsx has always used).
// Each figure carries its People judge (likability) when public ratings exist; see peopleData.js.
export const FAMOUS_FIGURES = ALL_FIGURES.filter((f, i, arr) => arr.findIndex(x => x.name === f.name) === i)
  .map(f => (PEOPLE[f.name] ? { ...f, people: PEOPLE[f.name] } : f));

// Sprite slug: lowercase, spaces -> '-', everything else non-alphanumeric stripped.
export function slugify(name) {
  return String(name).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "").replace(/-+/g, "-").replace(/^-|-$/g, "");
}

// The sprite pipeline may or may not fold accents ("pele" vs "pel"). Look up both.
export function slugCandidates(name) {
  const strict = String(name).toLowerCase().replace(/ /g, "-").replace(/[^a-z0-9-]/g, "");
  const folded = slugify(name);
  return strict === folded ? [folded] : [folded, strict];
}
