// GENERATED by scripts/seed-likability.mjs from docs/methodology/benchmarks.json. Do not hand-edit.
// The People judge for public figures: likability from YouGov US ratings (see src/cube.js likabilityFrom).
export const PEOPLE = {
 "Nikola Tesla": {
  "likability": 67,
  "source": "YouGov US ratings",
  "fame": 86,
  "liked": 61,
  "disliked": 6,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Nikola_Tesla"
 },
 "Genghis Khan": {
  "likability": 37,
  "source": "YouGov US ratings",
  "fame": 84,
  "liked": 28,
  "disliked": 25,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Genghis_Khan"
 },
 "Mahatma Gandhi": {
  "likability": 64,
  "source": "YouGov US ratings",
  "fame": 88,
  "liked": 59,
  "disliked": 9,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Mahatma_Gandhi"
 },
 "Elon Musk": {
  "likability": 36,
  "source": "YouGov US ratings",
  "fame": 98,
  "liked": 33,
  "disliked": 53,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Elon_Musk"
 },
 "Taylor Swift": {
  "likability": 52,
  "source": "YouGov US ratings",
  "fame": 98,
  "liked": 51,
  "disliked": 25,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Taylor_Swift"
 },
 "Kobe Bryant": {
  "likability": 62,
  "source": "YouGov US ratings",
  "fame": 92,
  "liked": 60,
  "disliked": 8,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Kobe_Bryant"
 },
 "Dennis Rodman": {
  "likability": 39,
  "source": "YouGov US ratings",
  "fame": 77,
  "liked": 28,
  "disliked": 26,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Dennis_Rodman"
 },
 "Sam Altman": {
  "likability": 34,
  "source": "YouGov US ratings",
  "fame": 57,
  "liked": 16,
  "disliked": 26,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Sam_Altman"
 },
 "Peter Thiel": {
  "likability": 32,
  "source": "YouGov US ratings",
  "fame": 52,
  "liked": 13,
  "disliked": 24,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Peter_Thiel"
 },
 "Pablo Picasso": {
  "likability": 71,
  "source": "YouGov US ratings",
  "fame": 90,
  "liked": 68,
  "disliked": 5,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Pablo_Picasso"
 },
 "Socrates": {
  "likability": 61,
  "source": "YouGov US ratings",
  "fame": 85,
  "liked": 54,
  "disliked": 5,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Socrates"
 },
 "Kim Jong-un": {
  "likability": 22,
  "source": "YouGov US ratings",
  "fame": 89,
  "liked": 14,
  "disliked": 65,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Kim_Jong_Un"
 },
 "Queen Elizabeth II": {
  "likability": 59,
  "source": "YouGov US ratings",
  "fame": 95,
  "liked": 58,
  "disliked": 11,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Queen_Elizabeth_II"
 },
 "Tom Brady": {
  "likability": 51,
  "source": "YouGov US ratings",
  "fame": 89,
  "liked": 46,
  "disliked": 18,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Tom_Brady"
 },
 "Shohei Ohtani": {
  "likability": 65,
  "source": "YouGov US ratings",
  "fame": 51,
  "liked": 36,
  "disliked": 4,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Shohei_Ohtani"
 },
 "Michael Jackson": {
  "likability": 66,
  "source": "YouGov US ratings",
  "fame": 97,
  "liked": 67,
  "disliked": 13,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Michael_Jackson"
 },
 "Madonna": {
  "likability": 53,
  "source": "YouGov US ratings",
  "fame": 95,
  "liked": 51,
  "disliked": 19,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Madonna"
 },
 "JFK": {
  "likability": 69,
  "source": "YouGov US ratings",
  "fame": 98,
  "liked": 71,
  "disliked": 3,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/John_F_Kennedy"
 },
 "Prince": {
  "likability": 69,
  "source": "YouGov US ratings",
  "fame": 95,
  "liked": 69,
  "disliked": 8,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Prince"
 },
 "Putin": {
  "likability": 26,
  "source": "YouGov US ratings",
  "fame": 95,
  "liked": 20,
  "disliked": 65,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Vladimir_Putin"
 },
 "Pelé": {
  "likability": 64,
  "source": "YouGov US ratings",
  "fame": 60,
  "liked": 41,
  "disliked": 4,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Pele"
 },
 "Keanu Reeves": {
  "likability": 78,
  "source": "YouGov US ratings",
  "fame": 96,
  "liked": 81,
  "disliked": 1,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Keanu_Reeves"
 },
 "Babe Ruth": {
  "likability": 72,
  "source": "YouGov US ratings",
  "fame": 90,
  "liked": 69,
  "disliked": 3,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Babe_Ruth"
 },
 "Jason Kelce": {
  "likability": 53,
  "source": "YouGov US ratings",
  "fame": 70,
  "liked": 38,
  "disliked": 11,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Jason_Kelce"
 },
 "Marie Curie": {
  "likability": 72,
  "source": "YouGov US ratings",
  "fame": 78,
  "liked": 61,
  "disliked": 2,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Marie_Curie"
 },
 "Albert Einstein": {
  "likability": 77,
  "source": "YouGov US ratings",
  "fame": 96,
  "liked": 79,
  "disliked": 2,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Albert_Einstein"
 },
 "Muhammad Ali": {
  "likability": 73,
  "source": "YouGov US ratings",
  "fame": 93,
  "liked": 73,
  "disliked": 4,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Muhammad_Ali"
 },
 "Martin Luther King Jr.": {
  "likability": 76,
  "source": "YouGov US ratings",
  "fame": 99,
  "liked": 81,
  "disliked": 4,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Martin_Luther_King_Jr"
 },
 "Leonardo da Vinci": {
  "likability": 79,
  "source": "YouGov US ratings",
  "fame": 92,
  "liked": 79,
  "disliked": 2,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Leonardo_da_Vinci"
 },
 "Isaac Newton": {
  "likability": 69,
  "source": "YouGov US ratings",
  "fame": 95,
  "liked": 69,
  "disliked": 1,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Isaac_Newton"
 },
 "Oprah Winfrey": {
  "likability": 42,
  "source": "YouGov US ratings",
  "fame": 98,
  "liked": 40,
  "disliked": 33,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Oprah_Winfrey"
 },
 "Bruce Lee": {
  "likability": 73,
  "source": "YouGov US ratings",
  "fame": 93,
  "liked": 73,
  "disliked": 2,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Bruce_Lee"
 },
 "George Orwell": {
  "likability": 68,
  "source": "YouGov US ratings",
  "fame": 74,
  "liked": 54,
  "disliked": 4,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/George_Orwell"
 },
 "Marcus Aurelius": {
  "likability": 51,
  "source": "YouGov US ratings",
  "fame": 67,
  "liked": 34,
  "disliked": 7,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Marcus_Aurelius"
 },
 "Nikola Jokic": {
  "likability": 61,
  "source": "YouGov US ratings",
  "fame": 44,
  "liked": 29,
  "disliked": 4,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Nikola_Jokic"
 },
 "Aretha Franklin": {
  "likability": 73,
  "source": "YouGov US ratings",
  "fame": 91,
  "liked": 71,
  "disliked": 4,
  "asOf": "2026-09-24",
  "url": "https://yougov.com/en-us/topics/public_figure/Aretha_Franklin"
 }
};
